# Generated by Django 5.2.12 on 2026-03-24 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_organizationaccessauditevent_action_type'),
        ('outbound', '0001_initial'),
        ('partners', '0002_customeraccount_operational_fields'),
        ('products', '0002_alter_productpackaging_height_cm_and_more'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('STANDARD', 'Standard'), ('B2B', 'B2B'), ('DROPSHIP', 'Dropshipping')], default='STANDARD', max_length=32)),
                ('return_number', models.CharField(max_length=64)),
                ('customer_code', models.CharField(blank=True, default='', max_length=64)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_contact_phone', models.CharField(blank=True, default='', max_length=64)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('reference_code', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL_RECEIVED', 'Partial Received'), ('RECEIVED', 'Received'), ('PARTIAL_DISPOSED', 'Partial Disposed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='partners.customeraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='organizations.organization')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='outbound.salesorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_orders', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-create_time', '-id'),
                'permissions': [('view_returns', 'Can view returns operations'), ('manage_return_orders', 'Can manage return orders'), ('manage_return_execution', 'Can manage return execution')],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('expected_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('received_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('disposed_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('return_reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL_RECEIVED', 'Partial Received'), ('RECEIVED', 'Received'), ('PARTIAL_DISPOSED', 'Partial Disposed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_lines', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_lines', to='products.product')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.returnorder')),
            ],
            options={
                'ordering': ('organization_id', 'return_order_id', 'line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReturnReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=64)),
                ('received_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('disposed_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='QUARANTINE', max_length=32)),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_by', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_receipts', to='inventory.inventorymovement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_receipts', to='organizations.organization')),
                ('receipt_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_receipts', to='locations.location')),
                ('return_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='returns.returnline')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_receipts', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-received_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReturnDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition_number', models.CharField(max_length=64)),
                ('disposition_type', models.CharField(choices=[('RESTOCK', 'Restock'), ('QUARANTINE', 'Quarantine'), ('SCRAP', 'Scrap')], max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_by', models.CharField(max_length=255)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_dispositions', to='inventory.inventorymovement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_dispositions', to='organizations.organization')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_dispositions', to='locations.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_dispositions', to='warehouse.warehouse')),
                ('return_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='returns.returnreceipt')),
            ],
            options={
                'ordering': ('organization_id', '-completed_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='returnorder',
            constraint=models.UniqueConstraint(fields=('organization', 'return_number'), name='unique_return_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.UniqueConstraint(fields=('return_order', 'line_number'), name='unique_return_line_number_per_order'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_qty__gte', models.F('received_qty'))), name='return_line_expected_gte_received'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty__gte', models.F('disposed_qty'))), name='return_line_received_gte_disposed'),
        ),
        migrations.AddConstraint(
            model_name='returnreceipt',
            constraint=models.UniqueConstraint(fields=('organization', 'receipt_number'), name='unique_return_receipt_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='returnreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty__gte', models.F('disposed_qty'))), name='return_receipt_received_gte_disposed'),
        ),
        migrations.AddConstraint(
            model_name='returndisposition',
            constraint=models.UniqueConstraint(fields=('organization', 'disposition_number'), name='unique_return_disposition_number_per_organization'),
        ),
    ]
