# Generated by Django 5.2.12 on 2026-03-24 02:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_alter_organizationaccessauditevent_action_type'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('on_hand_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('hold_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('organization_id', 'warehouse_id', 'location_id', 'product_id', 'id'),
                'permissions': [('view_inventory', 'Can view inventory'), ('manage_inventory_records', 'Can manage inventory records'), ('manage_inventory_configuration', 'Can manage inventory configuration')],
            },
        ),
        migrations.CreateModel(
            name='InventoryHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('reason', models.CharField(max_length=255)),
                ('reference_code', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('held_by', models.CharField(max_length=255)),
                ('released_by', models.CharField(blank=True, default='', max_length=255)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('organization_id', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('RECEIPT', 'Receipt'), ('PUTAWAY', 'Putaway'), ('TRANSFER', 'Transfer'), ('PICK', 'Pick'), ('SHIP', 'Ship'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('HOLD', 'Hold'), ('RELEASE_HOLD', 'Release Hold')], max_length=32)),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('reference_code', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('performed_by', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resulting_from_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('resulting_to_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
            ],
            options={
                'ordering': ('organization_id', '-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('direction', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease'), ('BOTH', 'Both')], default='BOTH', max_length=32)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment_reasons', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_variance_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('approver_role', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment_approval_rules', to='organizations.organization')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment_approval_rules', to='warehouse.warehouse')),
                ('adjustment_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='inventory.inventoryadjustmentreason')),
            ],
            options={
                'ordering': ('organization_id', 'adjustment_reason_id', '-minimum_variance_qty', 'approver_role', 'id'),
            },
        ),
    ]
