# Generated by Django 5.2.12 on 2026-03-24 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_organizationaccessauditevent_action_type'),
        ('products', '0001_initial'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybalance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='locations.location'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventorybalance',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='inventory_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='inventory.inventorybalance'),
        ),
        migrations.AddField(
            model_name='inventoryhold',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_holds', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements_out', to='locations.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements_in', to='locations.location'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='warehouse.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentreason',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_adjustment_reason_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='inventoryadjustmentapprovalrule',
            constraint=models.UniqueConstraint(fields=('organization', 'adjustment_reason', 'warehouse', 'minimum_variance_qty', 'approver_role'), name='unique_inventory_adjustment_approval_rule'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('location', 'product', 'lot_number', 'serial_number', 'stock_status'), name='unique_inventory_balance_slot'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_qty__gte', models.F('allocated_qty'))), name='inventory_on_hand_gte_allocated'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_qty__gte', models.F('hold_qty'))), name='inventory_on_hand_gte_hold'),
        ),
    ]
