# Generated by Django 5.2.12 on 2026-04-02 00:00

import django.core.validators
import django.db.models.deletion
from django.db.models import Q
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        ("organizations", "0004_alter_organizationaccessauditevent_action_type"),
        ("warehouse", "0002_alter_warehouse_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryInformationImportRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("merchant_sku", models.CharField(max_length=64)),
                ("product_name", models.CharField(blank=True, default="", max_length=255)),
                ("shelf", models.CharField(max_length=64)),
                (
                    "available_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))],
                    ),
                ),
                ("listing_time", models.DateField()),
                ("actual_length", models.CharField(blank=True, default="", max_length=32)),
                ("actual_width", models.CharField(blank=True, default="", max_length=32)),
                ("actual_height", models.CharField(blank=True, default="", max_length=32)),
                ("actual_weight", models.CharField(blank=True, default="", max_length=32)),
                ("measurement_unit", models.CharField(blank=True, default="", max_length=32)),
                ("merchant_code", models.CharField(blank=True, default="", max_length=64)),
                ("customer_code", models.CharField(blank=True, default="", max_length=64)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[("AVAILABLE", "Available"), ("QUARANTINE", "Quarantine"), ("DAMAGED", "Damaged")],
                        default="AVAILABLE",
                        max_length=32,
                    ),
                ),
                ("created_by", models.CharField(blank=True, default="", max_length=255)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_information_import_records",
                        to="organizations.organization",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_information_import_records",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "warehouse_id", "merchant_sku", "shelf", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="inventoryinformationimportrecord",
            constraint=models.UniqueConstraint(
                condition=Q(warehouse__isnull=True),
                fields=("organization", "merchant_sku"),
                name="unique_inventory_information_import_global_sku",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryinformationimportrecord",
            constraint=models.UniqueConstraint(
                condition=Q(warehouse__isnull=False),
                fields=("organization", "warehouse", "merchant_sku"),
                name="unique_inventory_information_import_scoped_sku",
            ),
        ),
    ]
