# Generated by Django 5.2.12 on 2026-03-24 22:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_alter_organizationaccessauditevent_action_type'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('INVENTORY_AGING', 'Inventory Aging'), ('RECEIVING_THROUGHPUT', 'Receiving Throughput'), ('SHIPPING_THROUGHPUT', 'Shipping Throughput')], max_length=32)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('EXPIRED', 'Expired')], default='GENERATED', max_length=16)),
                ('export_format', models.CharField(default='csv', max_length=16)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('file_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_report_exports', to='organizations.organization')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-generated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='WarehouseKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generated_by', models.CharField(max_length=255)),
                ('on_hand_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('available_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('hold_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('open_purchase_orders', models.PositiveIntegerField(default=0)),
                ('open_sales_orders', models.PositiveIntegerField(default=0)),
                ('open_putaway_tasks', models.PositiveIntegerField(default=0)),
                ('open_pick_tasks', models.PositiveIntegerField(default=0)),
                ('pending_count_approvals', models.PositiveIntegerField(default=0)),
                ('pending_return_orders', models.PositiveIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_kpi_snapshots', to='organizations.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_snapshots', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-snapshot_date', '-id'),
                'permissions': [('view_reporting', 'Can view reporting'), ('manage_reporting', 'Can manage reporting')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'warehouse', 'snapshot_date'), name='unique_reporting_kpi_snapshot_per_day')],
            },
        ),
    ]
