# Generated by Django 5.2.12 on 2026-03-24 03:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_organizationaccessauditevent_action_type'),
        ('products', '0002_alter_productpackaging_height_cm_and_more'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.CharField(max_length=64)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('is_blind_count', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COUNTED', 'Counted'), ('RECOUNT_IN_PROGRESS', 'Recount In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_by', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_counts', to='organizations.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_counts', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-create_time', '-id'),
                'permissions': [('view_counting', 'Can view counting operations'), ('manage_counting', 'Can manage counting operations')],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('system_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('variance_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COUNTED', 'Counted'), ('RECOUNT_ASSIGNED', 'Recount Assigned'), ('PENDING_APPROVAL', 'Pending Approval'), ('RECONCILED', 'Reconciled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('scanner_task_type', models.CharField(choices=[('NONE', 'None'), ('COUNT', 'Count'), ('RECOUNT', 'Recount')], default='NONE', max_length=16)),
                ('scanner_task_status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='UNASSIGNED', max_length=16)),
                ('scanner_task_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('scanner_task_started_at', models.DateTimeField(blank=True, null=True)),
                ('scanner_task_completed_at', models.DateTimeField(blank=True, null=True)),
                ('scanner_task_last_operator', models.CharField(blank=True, default='', max_length=255)),
                ('counted_by', models.CharField(blank=True, default='', max_length=255)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('recount_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('recount_counted_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('recounted_by', models.CharField(blank=True, default='', max_length=255)),
                ('recounted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('adjustment_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_lines', to='inventory.inventorymovement')),
                ('adjustment_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_lines', to='inventory.inventoryadjustmentreason')),
                ('assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cycle_count_lines', to='organizations.organizationmembership')),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='counting.cyclecount')),
                ('inventory_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_lines', to='inventory.inventorybalance')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_lines', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_lines', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_count_lines', to='products.product')),
                ('recount_assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recount_cycle_count_lines', to='organizations.organizationmembership')),
            ],
            options={
                'ordering': ('organization_id', 'cycle_count_id', 'line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CountApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_APPROVED', 'Auto Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, default='', max_length=255)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('approval_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_approvals', to='inventory.inventoryadjustmentapprovalrule')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_approvals', to='organizations.organization')),
                ('cycle_count_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='counting.cyclecountline')),
            ],
            options={
                'ordering': ('organization_id', '-requested_at', '-id'),
                'permissions': [('manage_count_approvals', 'Can manage counting approvals')],
            },
        ),
        migrations.AddConstraint(
            model_name='cyclecount',
            constraint=models.UniqueConstraint(fields=('organization', 'count_number'), name='unique_cycle_count_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountline',
            constraint=models.UniqueConstraint(fields=('cycle_count', 'line_number'), name='unique_cycle_count_line_number_per_count'),
        ),
    ]
