# Generated by Django 5.2.12 on 2026-03-14 02:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceShipmentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('asn_number', models.CharField(max_length=64, verbose_name='ASN Number')),
                ('expected_arrival_date', models.DateField(blank=True, null=True, verbose_name='Expected Arrival Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partial'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Advance Shipment Notice',
                'verbose_name_plural': 'Advance Shipment Notices',
                'db_table': 'inbound_advance_shipment_notice',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceShipmentNoticeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('line_number', models.PositiveIntegerField(verbose_name='Line Number')),
                ('expected_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Expected Qty')),
                ('received_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Received Qty')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('expected_lpn_code', models.CharField(blank=True, default='', max_length=128, verbose_name='Expected LPN Code')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Advance Shipment Notice Line',
                'verbose_name_plural': 'Advance Shipment Notice Lines',
                'db_table': 'inbound_advance_shipment_notice_line',
                'ordering': ['asn_id', 'line_number'],
            },
        ),
    ]
