# Generated by Django 5.2.12 on 2026-03-14 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_creater_creator'),
        ('inbound', '0002_advanceshipmentnotice_advanceshipmentnoticeline'),
        ('scanner', '0002_goodsscanrule_barcodealias_licenseplate'),
        ('supplier', '0002_rename_creater_creator'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='putawaytask',
            name='license_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='putaway_tasks', to='scanner.licenseplate', verbose_name='License Plate'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='license_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='scanner.licenseplate', verbose_name='License Plate'),
        ),
        migrations.AddField(
            model_name='advanceshipmentnotice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_shipment_notices', to='inbound.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='advanceshipmentnotice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_shipment_notices', to='supplier.listmodel', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='advanceshipmentnotice',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_shipment_notices', to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='asn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inbound.advanceshipmentnotice', verbose_name='Advance Shipment Notice'),
        ),
        migrations.AddField(
            model_name='advanceshipmentnoticeline',
            name='asn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inbound.advanceshipmentnotice', verbose_name='Advance Shipment Notice'),
        ),
        migrations.AddField(
            model_name='advanceshipmentnoticeline',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asn_lines', to='goods.listmodel', verbose_name='Goods'),
        ),
        migrations.AddField(
            model_name='advanceshipmentnoticeline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asn_lines', to='inbound.purchaseorderline', verbose_name='Purchase Order Line'),
        ),
        migrations.AddField(
            model_name='receiptline',
            name='asn_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='inbound.advanceshipmentnoticeline', verbose_name='ASN Line'),
        ),
        migrations.AddConstraint(
            model_name='advanceshipmentnotice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'asn_number'), name='inbound_asn_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='advanceshipmentnoticeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('asn', 'line_number'), name='inbound_asn_line_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='advanceshipmentnoticeline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_qty__gte', models.F('received_qty'))), name='inbound_asn_line_received_lte_expected'),
        ),
    ]
