# Generated by Django 5.2.12 on 2026-03-22 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbound", "0003_putawaytask_license_plate_receiptline_license_plate_and_more"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundImportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(default="system", max_length=255, verbose_name="Created By")),
                ("openid", models.CharField(db_index=True, max_length=255, verbose_name="Openid")),
                ("is_delete", models.BooleanField(default=False, verbose_name="Delete Label")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="Create Time")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="Update Time")),
                ("batch_number", models.CharField(max_length=64, verbose_name="Batch Number")),
                ("file_name", models.CharField(max_length=255, verbose_name="File Name")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("COMPLETED_WITH_ERRORS", "Completed With Errors"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0, verbose_name="Total Rows")),
                ("success_rows", models.PositiveIntegerField(default=0, verbose_name="Successful Rows")),
                ("failed_rows", models.PositiveIntegerField(default=0, verbose_name="Failed Rows")),
                ("summary", models.TextField(blank=True, default="", verbose_name="Summary")),
                ("failure_rows", models.JSONField(blank=True, default=list, verbose_name="Failure Rows")),
                ("imported_by", models.CharField(max_length=255, verbose_name="Imported By")),
                ("imported_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Imported At")),
            ],
            options={
                "verbose_name": "Inbound Import Batch",
                "verbose_name_plural": "Inbound Import Batches",
                "db_table": "inbound_import_batch",
                "ordering": ["-imported_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InboundSigningRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(default="system", max_length=255, verbose_name="Created By")),
                ("openid", models.CharField(db_index=True, max_length=255, verbose_name="Openid")),
                ("is_delete", models.BooleanField(default=False, verbose_name="Delete Label")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="Create Time")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="Update Time")),
                ("signing_number", models.CharField(max_length=64, verbose_name="Signing Number")),
                ("reference_code", models.CharField(blank=True, default="", max_length=64, verbose_name="Reference Code")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                ("carrier_name", models.CharField(blank=True, default="", max_length=255, verbose_name="Carrier Name")),
                ("vehicle_plate", models.CharField(blank=True, default="", max_length=64, verbose_name="Vehicle Plate")),
                ("signed_by", models.CharField(max_length=255, verbose_name="Signed By")),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Signed At")),
                (
                    "asn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signing_records",
                        to="inbound.advanceshipmentnotice",
                        verbose_name="Advance Shipment Notice",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signing_records",
                        to="inbound.purchaseorder",
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_signing_records",
                        to="warehouse.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inbound Signing Record",
                "verbose_name_plural": "Inbound Signing Records",
                "db_table": "inbound_signing_record",
                "ordering": ["-signed_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="inboundimportbatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_delete", False)),
                fields=("openid", "batch_number"),
                name="inbound_import_batch_number_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundsigningrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_delete", False)),
                fields=("openid", "signing_number"),
                name="inbound_signing_number_uq",
            ),
        ),
    ]
