# Generated by Django 5.2.12 on 2026-03-22 00:00

from django.db import migrations, models


ORDER_TYPE_CHOICES = [
    ("STANDARD", "Standard"),
    ("B2B", "B2B"),
    ("DROPSHIP", "Dropshipping"),
]


def backfill_asn_order_type(apps, schema_editor):
    AdvanceShipmentNotice = apps.get_model("inbound", "AdvanceShipmentNotice")

    for asn in AdvanceShipmentNotice.objects.select_related("purchase_order").all().iterator():
        purchase_order = asn.purchase_order
        asn.order_type = getattr(purchase_order, "order_type", "STANDARD") or "STANDARD"
        asn.save(update_fields=["order_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("inbound", "0004_inboundimportbatch_inboundsigningrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="order_type",
            field=models.CharField(
                choices=ORDER_TYPE_CHOICES,
                default="STANDARD",
                max_length=32,
                verbose_name="Order Type",
            ),
        ),
        migrations.AddField(
            model_name="advanceshipmentnotice",
            name="order_type",
            field=models.CharField(
                choices=ORDER_TYPE_CHOICES,
                default="STANDARD",
                max_length=32,
                verbose_name="Order Type",
            ),
        ),
        migrations.RunPython(backfill_asn_order_type, migrations.RunPython.noop),
    ]
