services:
  backend:
    build:
      context: ./backend
    container_name: dachong_wms_backend
    environment:
      DJANGO_SETTINGS_MODULE: dachong_wms.settings
    depends_on:
      - db

  frontend:
    container_name: dachong_wms_frontend
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres_db
    volumes:
      - db_data_pg16:/var/lib/postgresql/data

volumes:
  db_data_pg16:
  frontend_node_modules:
