"""Warehouse KPI, export, and 3PL billing models."""

from __future__ import annotations

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Q
from django.utils import timezone


class TenantAuditModel(models.Model):
    creator = models.CharField(max_length=255, default="system", verbose_name="Created By")
    openid = models.CharField(max_length=255, verbose_name="Openid", db_index=True)
    is_delete = models.BooleanField(default=False, verbose_name="Delete Label")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="Create Time")
    update_time = models.DateTimeField(auto_now=True, verbose_name="Update Time")

    class Meta:
        abstract = True


class OperationalReportType(models.TextChoices):
    INVENTORY_AGING = "INVENTORY_AGING", "Inventory Aging"
    RECEIVING_THROUGHPUT = "RECEIVING_THROUGHPUT", "Receiving Throughput"
    SHIPPING_THROUGHPUT = "SHIPPING_THROUGHPUT", "Shipping Throughput"


class OperationalReportStatus(models.TextChoices):
    GENERATED = "GENERATED", "Generated"
    EXPIRED = "EXPIRED", "Expired"


class BillingChargeType(models.TextChoices):
    STORAGE_DAILY = "STORAGE_DAILY", "Storage Daily"
    RECEIPT_HANDLING = "RECEIPT_HANDLING", "Receipt Handling"
    SHIPMENT_HANDLING = "SHIPMENT_HANDLING", "Shipment Handling"
    RETURN_HANDLING = "RETURN_HANDLING", "Return Handling"
    LABEL_GENERATION = "LABEL_GENERATION", "Label Generation"
    EXTRA_SCAN = "EXTRA_SCAN", "Extra Scan"


class BillingChargeStatus(models.TextChoices):
    OPEN = "OPEN", "Open"
    INVOICED = "INVOICED", "Invoiced"
    VOID = "VOID", "Void"


class InvoiceStatus(models.TextChoices):
    DRAFT = "DRAFT", "Draft"
    FINALIZED = "FINALIZED", "Finalized"
    VOID = "VOID", "Void"


class StorageAccrualStatus(models.TextChoices):
    GENERATED = "GENERATED", "Generated"
    VOID = "VOID", "Void"


class FinanceApprovalStatus(models.TextChoices):
    PENDING = "PENDING", "Pending"
    APPROVED = "APPROVED", "Approved"
    REJECTED = "REJECTED", "Rejected"


class FinanceExportStatus(models.TextChoices):
    GENERATED = "GENERATED", "Generated"
    EXPIRED = "EXPIRED", "Expired"


class WarehouseKpiSnapshot(TenantAuditModel):
    warehouse = models.ForeignKey(
        "warehouse.Warehouse",
        on_delete=models.PROTECT,
        related_name="kpi_snapshots",
        verbose_name="Warehouse",
    )
    snapshot_date = models.DateField(verbose_name="Snapshot Date")
    generated_at = models.DateTimeField(default=timezone.now, verbose_name="Generated At")
    generated_by = models.CharField(max_length=255, verbose_name="Generated By")
    on_hand_qty = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"), verbose_name="On Hand Qty")
    available_qty = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"), verbose_name="Available Qty")
    allocated_qty = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"), verbose_name="Allocated Qty")
    hold_qty = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"), verbose_name="Hold Qty")
    open_purchase_orders = models.PositiveIntegerField(default=0, verbose_name="Open Purchase Orders")
    open_sales_orders = models.PositiveIntegerField(default=0, verbose_name="Open Sales Orders")
    open_putaway_tasks = models.PositiveIntegerField(default=0, verbose_name="Open Putaway Tasks")
    open_pick_tasks = models.PositiveIntegerField(default=0, verbose_name="Open Pick Tasks")
    pending_count_approvals = models.PositiveIntegerField(default=0, verbose_name="Pending Count Approvals")
    pending_return_orders = models.PositiveIntegerField(default=0, verbose_name="Pending Return Orders")

    class Meta:
        db_table = "reporting_warehouse_kpi_snapshot"
        verbose_name = "Warehouse KPI Snapshot"
        verbose_name_plural = "Warehouse KPI Snapshots"
        ordering = ["-snapshot_date", "-id"]
        constraints = [
            models.UniqueConstraint(
                fields=["openid", "warehouse", "snapshot_date"],
                condition=Q(is_delete=False),
                name="reporting_kpi_snapshot_unique",
            ),
        ]

    def __str__(self) -> str:  # pragma: no cover
        return f"{self.warehouse_id}:{self.snapshot_date}"


class OperationalReportExport(TenantAuditModel):
    warehouse = models.ForeignKey(
        "warehouse.Warehouse",
        on_delete=models.PROTECT,
        related_name="report_exports",
        blank=True,
        null=True,
        verbose_name="Warehouse",
    )
    report_type = models.CharField(max_length=32, choices=OperationalReportType.choices, verbose_name="Report Type")
    status = models.CharField(
        max_length=16,
        choices=OperationalReportStatus.choices,
        default=OperationalReportStatus.GENERATED,
        verbose_name="Status",
    )
    export_format = models.CharField(max_length=16, default="csv", verbose_name="Export Format")
    date_from = models.DateField(blank=True, null=True, verbose_name="Date From")
    date_to = models.DateField(blank=True, null=True, verbose_name="Date To")
    parameters = models.JSONField(default=dict, blank=True, verbose_name="Parameters")
    file_name = models.CharField(max_length=255, verbose_name="File Name")
    row_count = models.PositiveIntegerField(default=0, verbose_name="Row Count")
    generated_at = models.DateTimeField(default=timezone.now, verbose_name="Generated At")
    generated_by = models.CharField(max_length=255, verbose_name="Generated By")
    content = models.TextField(blank=True, default="", verbose_name="Content")

    class Meta:
        db_table = "reporting_operational_report_export"
        verbose_name = "Operational Report Export"
        verbose_name_plural = "Operational Report Exports"
        ordering = ["-generated_at", "-id"]

    def __str__(self) -> str:  # pragma: no cover
        return self.file_name


class BillingChargeEvent(TenantAuditModel):
    warehouse = models.ForeignKey(
        "warehouse.Warehouse",
        on_delete=models.PROTECT,
        related_name="billing_charge_events",
        verbose_name="Warehouse",
    )
    customer = models.ForeignKey(
        "customer.ListModel",
        on_delete=models.PROTECT,
        related_name="billing_charge_events",
        blank=True,
        null=True,
        verbose_name="Customer",
    )
    rate_contract = models.ForeignKey(
        "reporting.BillingRateContract",
        on_delete=models.PROTECT,
        related_name="charge_events",
        blank=True,
        null=True,
        verbose_name="Rate Contract",
    )
    charge_type = models.CharField(max_length=32, choices=BillingChargeType.choices, verbose_name="Charge Type")
    event_date = models.DateField(verbose_name="Event Date")
    quantity = models.DecimalField(
        max_digits=18,
        decimal_places=4,
        validators=[MinValueValidator(Decimal("0.0000"))],
        verbose_name="Quantity",
    )
    uom = models.CharField(max_length=16, default="EA", verbose_name="UOM")
    unit_rate = models.DecimalField(
        max_digits=18,
        decimal_places=4,
        default=Decimal("0.0000"),
        validators=[MinValueValidator(Decimal("0.0000"))],
        verbose_name="Unit Rate",
    )
    amount = models.DecimalField(
        max_digits=18,
        decimal_places=4,
        default=Decimal("0.0000"),
        validators=[MinValueValidator(Decimal("0.0000"))],
        verbose_name="Amount",
    )
    currency = models.CharField(max_length=8, default="USD", verbose_name="Currency")
    status = models.CharField(
        max_length=16,
        choices=BillingChargeStatus.choices,
        default=BillingChargeStatus.OPEN,
        verbose_name="Status",
    )
    source_module = models.CharField(max_length=64, blank=True, default="", verbose_name="Source Module")
    source_record_type = models.CharField(max_length=64, blank=True, default="", verbose_name="Source Record Type")
    source_record_id = models.PositiveBigIntegerField(blank=True, null=True, verbose_name="Source Record ID")
    reference_code = models.CharField(max_length=64, blank=True, default="", verbose_name="Reference Code")
    notes = models.TextField(blank=True, default="", verbose_name="Notes")
    rated_at = models.DateTimeField(blank=True, null=True, verbose_name="Rated At")
    rated_by = models.CharField(max_length=255, blank=True, default="", verbose_name="Rated By")

    class Meta:
        db_table = "reporting_billing_charge_event"
        verbose_name = "Billing Charge Event"
        verbose_name_plural = "Billing Charge Events"
        ordering = ["-event_date", "-id"]
        constraints = [
            models.UniqueConstraint(
                fields=["openid", "charge_type", "source_module", "source_record_type", "source_record_id"],
                condition=Q(is_delete=False, source_record_id__isnull=False),
                name="reporting_charge_event_source_unique",
            ),
        ]

    def __str__(self) -> str:  # pragma: no cover
        return f"{self.charge_type}:{self.reference_code}"


class BillingRateContract(TenantAuditModel):
    warehouse = models.ForeignKey(
        "warehouse.Warehouse",
        on_delete=models.PROTECT,
        related_name="billing_rate_contracts",
        verbose_name="Warehouse",
    )
    customer = models.ForeignKey(
        "customer.ListModel",
        on_delete=models.PROTECT,
        related_name="billing_rate_contracts",
        blank=True,
        null=True,
        verbose_name="Customer",
    )
    contract_name = models.CharField(max_length=128, verbose_name="Contract Name")
    charge_type = models.CharField(max_length=32, choices=BillingChargeType.choices, verbose_name="Charge Type")
    unit_rate = models.DecimalField(
        max_digits=18,
        decimal_places=4,
        validators=[MinValueValidator(Decimal("0.0000"))],
        verbose_name="Unit Rate",
    )
    minimum_charge = models.DecimalField(
        max_digits=18,
        decimal_places=4,
        default=Decimal("0.0000"),
        validators=[MinValueValidator(Decimal("0.0000"))],
        verbose_name="Minimum Charge",
    )
    currency = models.CharField(max_length=8, default="USD", verbose_name="Currency")
    uom = models.CharField(max_length=16, default="EA", verbose_name="UOM")
    priority = models.PositiveIntegerField(default=100, verbose_name="Priority")
    effective_from = models.DateField(verbose_name="Effective From")
    effective_to = models.DateField(blank=True, null=True, verbose_name="Effective To")
    is_active = models.BooleanField(default=True, verbose_name="Is Active")
    notes = models.TextField(blank=True, default="", verbose_name="Notes")

    class Meta:
        db_table = "reporting_billing_rate_contract"
        verbose_name = "Billing Rate Contract"
        verbose_name_plural = "Billing Rate Contracts"
        ordering = ["priority", "-effective_from", "id"]
        constraints = [
            models.UniqueConstraint(
                fields=["openid", "warehouse", "customer", "charge_type", "contract_name", "effective_from"],
                condition=Q(is_delete=False),
                name="reporting_rate_contract_unique",
            ),
        ]

    def __str__(self) -> str:  # pragma: no cover
        return self.contract_name


class Invoice(TenantAuditModel):
    warehouse = models.ForeignKey(
        "warehouse.Warehouse",
        on_delete=models.PROTECT,
        related_name="invoices",
        verbose_name="Warehouse",
    )
    customer = models.ForeignKey(
        "customer.ListModel",
        on_delete=models.PROTECT,
        related_name="invoices",
        verbose_name="Customer",
    )
    invoice_number = models.CharField(max_length=64, verbose_name="Invoice Number")
    period_start = models.DateField(verbose_name="Period Start")
    period_end = models.DateField(verbose_name="Period End")
    status = models.CharField(
        max_length=16,
        choices=InvoiceStatus.choices,
        default=InvoiceStatus.DRAFT,
        verbose_name="Status",
    )
    currency = models.CharField(max_length=8, default="USD", verbose_name="Currency")
    subtotal_amount = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"), verbose_name="Subtotal Amount")
    tax_amount = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"), verbose_name="Tax Amount")
    total_amount = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"), verbose_name="Total Amount")
    generated_at = models.DateTimeField(default=timezone.now, verbose_name="Generated At")
    generated_by = models.CharField(max_length=255, verbose_name="Generated By")
    finalized_at = models.DateTimeField(blank=True, null=True, verbose_name="Finalized At")
    finalized_by = models.CharField(max_length=255, blank=True, default="", verbose_name="Finalized By")
    notes = models.TextField(blank=True, default="", verbose_name="Notes")

    class Meta:
        db_table = "reporting_invoice"
        verbose_name = "Invoice"
        verbose_name_plural = "Invoices"
        ordering = ["-generated_at", "-id"]
        constraints = [
            models.UniqueConstraint(
                fields=["openid", "invoice_number"],
                condition=Q(is_delete=False),
                name="reporting_invoice_number_unique",
            ),
        ]

    def __str__(self) -> str:  # pragma: no cover
        return self.invoice_number


class InvoiceLine(TenantAuditModel):
    invoice = models.ForeignKey(
        Invoice,
        on_delete=models.PROTECT,
        related_name="lines",
        verbose_name="Invoice",
    )
    charge_event = models.OneToOneField(
        BillingChargeEvent,
        on_delete=models.PROTECT,
        related_name="invoice_line",
        verbose_name="Billing Charge Event",
    )
    charge_type = models.CharField(max_length=32, choices=BillingChargeType.choices, verbose_name="Charge Type")
    event_date = models.DateField(verbose_name="Event Date")
    quantity = models.DecimalField(max_digits=18, decimal_places=4, verbose_name="Quantity")
    uom = models.CharField(max_length=16, default="EA", verbose_name="UOM")
    unit_rate = models.DecimalField(max_digits=18, decimal_places=4, verbose_name="Unit Rate")
    amount = models.DecimalField(max_digits=18, decimal_places=4, verbose_name="Amount")
    description = models.CharField(max_length=255, blank=True, default="", verbose_name="Description")
    reference_code = models.CharField(max_length=64, blank=True, default="", verbose_name="Reference Code")

    class Meta:
        db_table = "reporting_invoice_line"
        verbose_name = "Invoice Line"
        verbose_name_plural = "Invoice Lines"
        ordering = ["invoice_id", "id"]

    def __str__(self) -> str:  # pragma: no cover
        return f"{self.invoice.invoice_number}:{self.charge_event_id}"


class StorageAccrualRun(TenantAuditModel):
    warehouse = models.ForeignKey(
        "warehouse.Warehouse",
        on_delete=models.PROTECT,
        related_name="storage_accrual_runs",
        verbose_name="Warehouse",
    )
    customer = models.ForeignKey(
        "customer.ListModel",
        on_delete=models.PROTECT,
        related_name="storage_accrual_runs",
        verbose_name="Customer",
    )
    accrual_date = models.DateField(verbose_name="Accrual Date")
    status = models.CharField(
        max_length=16,
        choices=StorageAccrualStatus.choices,
        default=StorageAccrualStatus.GENERATED,
        verbose_name="Status",
    )
    basis = models.CharField(max_length=64, default="CURRENT_ON_HAND_SNAPSHOT", verbose_name="Basis")
    balance_count = models.PositiveIntegerField(default=0, verbose_name="Balance Count")
    total_on_hand_qty = models.DecimalField(
        max_digits=18,
        decimal_places=4,
        default=Decimal("0.0000"),
        validators=[MinValueValidator(Decimal("0.0000"))],
        verbose_name="Total On Hand Qty",
    )
    generated_at = models.DateTimeField(default=timezone.now, verbose_name="Generated At")
    generated_by = models.CharField(max_length=255, verbose_name="Generated By")
    charge_event = models.OneToOneField(
        BillingChargeEvent,
        on_delete=models.PROTECT,
        related_name="storage_accrual_run",
        blank=True,
        null=True,
        verbose_name="Charge Event",
    )
    notes = models.TextField(blank=True, default="", verbose_name="Notes")

    class Meta:
        db_table = "reporting_storage_accrual_run"
        verbose_name = "Storage Accrual Run"
        verbose_name_plural = "Storage Accrual Runs"
        ordering = ["-accrual_date", "-id"]
        constraints = [
            models.UniqueConstraint(
                fields=["openid", "warehouse", "customer", "accrual_date"],
                condition=Q(is_delete=False),
                name="reporting_storage_accrual_run_unique",
            ),
        ]

    def __str__(self) -> str:  # pragma: no cover
        return f"{self.customer_id}:{self.accrual_date}"


class InvoiceFinanceApproval(TenantAuditModel):
    invoice = models.OneToOneField(
        Invoice,
        on_delete=models.PROTECT,
        related_name="finance_approval",
        verbose_name="Invoice",
    )
    status = models.CharField(
        max_length=16,
        choices=FinanceApprovalStatus.choices,
        default=FinanceApprovalStatus.PENDING,
        verbose_name="Status",
    )
    submitted_at = models.DateTimeField(default=timezone.now, verbose_name="Submitted At")
    submitted_by = models.CharField(max_length=255, verbose_name="Submitted By")
    reviewed_at = models.DateTimeField(blank=True, null=True, verbose_name="Reviewed At")
    reviewed_by = models.CharField(max_length=255, blank=True, default="", verbose_name="Reviewed By")
    notes = models.TextField(blank=True, default="", verbose_name="Notes")

    class Meta:
        db_table = "reporting_invoice_finance_approval"
        verbose_name = "Invoice Finance Approval"
        verbose_name_plural = "Invoice Finance Approvals"
        ordering = ["-submitted_at", "-id"]

    def __str__(self) -> str:  # pragma: no cover
        return f"{self.invoice.invoice_number}:{self.status}"


class FinanceExport(TenantAuditModel):
    warehouse = models.ForeignKey(
        "warehouse.Warehouse",
        on_delete=models.PROTECT,
        related_name="finance_exports",
        blank=True,
        null=True,
        verbose_name="Warehouse",
    )
    customer = models.ForeignKey(
        "customer.ListModel",
        on_delete=models.PROTECT,
        related_name="finance_exports",
        blank=True,
        null=True,
        verbose_name="Customer",
    )
    status = models.CharField(
        max_length=16,
        choices=FinanceExportStatus.choices,
        default=FinanceExportStatus.GENERATED,
        verbose_name="Status",
    )
    export_format = models.CharField(max_length=16, default="csv", verbose_name="Export Format")
    period_start = models.DateField(verbose_name="Period Start")
    period_end = models.DateField(verbose_name="Period End")
    parameters = models.JSONField(default=dict, blank=True, verbose_name="Parameters")
    file_name = models.CharField(max_length=255, verbose_name="File Name")
    row_count = models.PositiveIntegerField(default=0, verbose_name="Row Count")
    generated_at = models.DateTimeField(default=timezone.now, verbose_name="Generated At")
    generated_by = models.CharField(max_length=255, verbose_name="Generated By")
    content = models.TextField(blank=True, default="", verbose_name="Content")

    class Meta:
        db_table = "reporting_finance_export"
        verbose_name = "Finance Export"
        verbose_name_plural = "Finance Exports"
        ordering = ["-generated_at", "-id"]

    def __str__(self) -> str:  # pragma: no cover
        return self.file_name
