from django.urls import path

from .views import (
    OrganizationCustomerLogisticsChannelDetailAPIView,
    OrganizationCustomerLogisticsChannelListCreateAPIView,
    OrganizationFuelRuleDetailAPIView,
    OrganizationFuelRuleListCreateAPIView,
    OrganizationLogisticsChargeDetailAPIView,
    OrganizationLogisticsChargeListCreateAPIView,
    OrganizationLogisticsChargingStrategyDetailAPIView,
    OrganizationLogisticsChargingStrategyListCreateAPIView,
    OrganizationLogisticsCostDetailAPIView,
    OrganizationLogisticsCostListCreateAPIView,
    OrganizationLogisticsGroupDetailAPIView,
    OrganizationLogisticsGroupListCreateAPIView,
    OrganizationLogisticsProviderChannelDetailAPIView,
    OrganizationLogisticsProviderChannelListCreateAPIView,
    OrganizationLogisticsProviderDetailAPIView,
    OrganizationLogisticsProviderListCreateAPIView,
    OrganizationLogisticsRuleDetailAPIView,
    OrganizationLogisticsRuleListCreateAPIView,
    OrganizationPartitionRuleDetailAPIView,
    OrganizationPartitionRuleListCreateAPIView,
    OrganizationRemoteAreaRuleDetailAPIView,
    OrganizationRemoteAreaRuleListCreateAPIView,
    OrganizationSpecialCustomerLogisticsChargingDetailAPIView,
    OrganizationSpecialCustomerLogisticsChargingListCreateAPIView,
    OrganizationWaybillWatermarkDetailAPIView,
    OrganizationWaybillWatermarkListCreateAPIView,
)

urlpatterns = [
    path(
        "organizations/<int:organization_id>/logistics/providers/",
        OrganizationLogisticsProviderListCreateAPIView.as_view(),
        name="organization-logistics-provider-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/providers/<int:provider_id>/",
        OrganizationLogisticsProviderDetailAPIView.as_view(),
        name="organization-logistics-provider-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/provider-channels/",
        OrganizationLogisticsProviderChannelListCreateAPIView.as_view(),
        name="organization-logistics-provider-channel-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/provider-channels/<int:provider_channel_id>/",
        OrganizationLogisticsProviderChannelDetailAPIView.as_view(),
        name="organization-logistics-provider-channel-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/customer-channels/",
        OrganizationCustomerLogisticsChannelListCreateAPIView.as_view(),
        name="organization-customer-logistics-channel-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/customer-channels/<int:customer_channel_id>/",
        OrganizationCustomerLogisticsChannelDetailAPIView.as_view(),
        name="organization-customer-logistics-channel-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/groups/",
        OrganizationLogisticsGroupListCreateAPIView.as_view(),
        name="organization-logistics-group-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/groups/<int:logistics_group_id>/",
        OrganizationLogisticsGroupDetailAPIView.as_view(),
        name="organization-logistics-group-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/rules/",
        OrganizationLogisticsRuleListCreateAPIView.as_view(),
        name="organization-logistics-rule-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/rules/<int:logistics_rule_id>/",
        OrganizationLogisticsRuleDetailAPIView.as_view(),
        name="organization-logistics-rule-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/partition-rules/",
        OrganizationPartitionRuleListCreateAPIView.as_view(),
        name="organization-partition-rule-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/partition-rules/<int:partition_rule_id>/",
        OrganizationPartitionRuleDetailAPIView.as_view(),
        name="organization-partition-rule-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/remote-area-rules/",
        OrganizationRemoteAreaRuleListCreateAPIView.as_view(),
        name="organization-remote-area-rule-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/remote-area-rules/<int:remote_area_rule_id>/",
        OrganizationRemoteAreaRuleDetailAPIView.as_view(),
        name="organization-remote-area-rule-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/fuel-rules/",
        OrganizationFuelRuleListCreateAPIView.as_view(),
        name="organization-fuel-rule-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/fuel-rules/<int:fuel_rule_id>/",
        OrganizationFuelRuleDetailAPIView.as_view(),
        name="organization-fuel-rule-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/waybill-watermarks/",
        OrganizationWaybillWatermarkListCreateAPIView.as_view(),
        name="organization-waybill-watermark-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/waybill-watermarks/<int:waybill_watermark_id>/",
        OrganizationWaybillWatermarkDetailAPIView.as_view(),
        name="organization-waybill-watermark-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/charging-strategies/",
        OrganizationLogisticsChargingStrategyListCreateAPIView.as_view(),
        name="organization-logistics-charging-strategy-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/charging-strategies/<int:charging_strategy_id>/",
        OrganizationLogisticsChargingStrategyDetailAPIView.as_view(),
        name="organization-logistics-charging-strategy-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/special-customer-charging/",
        OrganizationSpecialCustomerLogisticsChargingListCreateAPIView.as_view(),
        name="organization-special-customer-logistics-charging-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/special-customer-charging/<int:special_customer_charging_id>/",
        OrganizationSpecialCustomerLogisticsChargingDetailAPIView.as_view(),
        name="organization-special-customer-logistics-charging-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/charges/",
        OrganizationLogisticsChargeListCreateAPIView.as_view(),
        name="organization-logistics-charge-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/charges/<int:logistics_charge_id>/",
        OrganizationLogisticsChargeDetailAPIView.as_view(),
        name="organization-logistics-charge-detail",
    ),
    path(
        "organizations/<int:organization_id>/logistics/costs/",
        OrganizationLogisticsCostListCreateAPIView.as_view(),
        name="organization-logistics-cost-list",
    ),
    path(
        "organizations/<int:organization_id>/logistics/costs/<int:logistics_cost_id>/",
        OrganizationLogisticsCostDetailAPIView.as_view(),
        name="organization-logistics-cost-detail",
    ),
]

