# Generated by Django 5.2.12 on 2026-03-24 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_organizationaccessauditevent_action_type'),
        ('partners', '0002_customeraccount_operational_fields'),
        ('products', '0002_alter_productpackaging_height_cm_and_more'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('STANDARD', 'Standard'), ('B2B', 'B2B'), ('DROPSHIP', 'Dropshipping')], default='STANDARD', max_length=32)),
                ('po_number', models.CharField(max_length=64)),
                ('customer_code', models.CharField(blank=True, default='', max_length=64)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=64)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_contact_phone', models.CharField(blank=True, default='', max_length=64)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('reference_code', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partial'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='partners.customeraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='organizations.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-create_time', '-id'),
                'permissions': [('view_inbound', 'Can view inbound operations'), ('manage_inbound_orders', 'Can manage inbound orders'), ('manage_inbound_execution', 'Can manage inbound execution')],
            },
        ),
        migrations.CreateModel(
            name='AdvanceShipmentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('STANDARD', 'Standard'), ('B2B', 'B2B'), ('DROPSHIP', 'Dropshipping')], default='STANDARD', max_length=32)),
                ('asn_number', models.CharField(max_length=64)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partial'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('reference_code', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_shipment_notices', to='partners.customeraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_shipment_notices', to='organizations.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_shipment_notices', to='warehouse.warehouse')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_shipment_notices', to='inbound.purchaseorder')),
            ],
            options={
                'ordering': ('organization_id', '-create_time', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('ordered_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('received_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partial'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_lines', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_lines', to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inbound.purchaseorder')),
            ],
            options={
                'ordering': ('organization_id', 'purchase_order_id', 'line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AdvanceShipmentNoticeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('expected_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('received_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('expected_lpn_code', models.CharField(blank=True, default='', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inbound.advanceshipmentnotice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_shipment_notice_lines', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asn_lines', to='products.product')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asn_lines', to='inbound.purchaseorderline')),
            ],
            options={
                'ordering': ('organization_id', 'asn_id', 'line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=32)),
                ('reference_code', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_by', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='inbound.advanceshipmentnotice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='organizations.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inbound.purchaseorder')),
                ('receipt_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='locations.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-received_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('asn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='inbound.advanceshipmentnoticeline')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='inventory.inventorymovement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='products.product')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='inbound.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inbound.receipt')),
                ('receipt_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='locations.location')),
            ],
            options={
                'ordering': ('organization_id', 'receipt_id', 'purchase_order_line_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PutawayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('completed_by', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to='organizations.organizationmembership')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks_from', to='locations.location')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaway_tasks', to='inventory.inventorymovement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks', to='products.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks_to', to='locations.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks', to='warehouse.warehouse')),
                ('receipt_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putaway_tasks', to='inbound.receiptline')),
            ],
            options={
                'ordering': ('organization_id', 'status', 'create_time', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('organization', 'po_number'), name='unique_purchase_order_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='advanceshipmentnotice',
            constraint=models.UniqueConstraint(fields=('organization', 'asn_number'), name='unique_asn_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'line_number'), name='unique_purchase_order_line_number_per_order'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gte', models.F('received_qty'))), name='purchase_order_line_received_lte_ordered'),
        ),
        migrations.AddConstraint(
            model_name='advanceshipmentnoticeline',
            constraint=models.UniqueConstraint(fields=('asn', 'line_number'), name='unique_asn_line_number_per_asn'),
        ),
        migrations.AddConstraint(
            model_name='advanceshipmentnoticeline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_qty__gte', models.F('received_qty'))), name='asn_line_received_lte_expected'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('organization', 'receipt_number'), name='unique_receipt_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='receiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'purchase_order_line'), name='unique_receipt_line_per_receipt_po_line'),
        ),
        migrations.AddConstraint(
            model_name='putawaytask',
            constraint=models.UniqueConstraint(fields=('organization', 'task_number'), name='unique_putaway_task_number_per_organization'),
        ),
    ]
