# Generated by Django 5.2.12 on 2026-03-13 10:52

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_APPROVED', 'Auto Approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32, verbose_name='Status')),
                ('requested_by', models.CharField(max_length=255, verbose_name='Requested By')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Requested At')),
                ('approved_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Approved By')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejected_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Rejected By')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Count Approval',
                'verbose_name_plural': 'Count Approvals',
                'db_table': 'counting_count_approval',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('count_number', models.CharField(max_length=64, verbose_name='Cycle Count Number')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Scheduled Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COUNTED', 'Counted'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('submitted_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Submitted By')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Cycle Count',
                'verbose_name_plural': 'Cycle Counts',
                'db_table': 'counting_cycle_count',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('line_number', models.PositiveIntegerField(verbose_name='Line Number')),
                ('stock_status', models.CharField(max_length=32, verbose_name='Stock Status')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('system_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='System Qty')),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Counted Qty')),
                ('variance_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Variance Qty')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COUNTED', 'Counted'), ('PENDING_APPROVAL', 'Pending Approval'), ('RECONCILED', 'Reconciled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('counted_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Counted By')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='Counted At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Cycle Count Line',
                'verbose_name_plural': 'Cycle Count Lines',
                'db_table': 'counting_cycle_count_line',
                'ordering': ['cycle_count_id', 'line_number'],
            },
        ),
    ]
