# Generated by Django 5.2.12 on 2026-03-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counting', '0001_initial'),
        ('goods', '0002_rename_creater_creator'),
        ('inventory', '0002_inventoryadjustmentreason_and_more'),
        ('locations', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countapproval',
            name='approval_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='count_approvals', to='inventory.inventoryadjustmentapprovalrule', verbose_name='Approval Rule'),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_counts', to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='adjustment_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='inventory.inventorymovement', verbose_name='Adjustment Movement'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='adjustment_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='inventory.inventoryadjustmentreason', verbose_name='Adjustment Reason'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='cycle_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='counting.cyclecount', verbose_name='Cycle Count'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='goods.listmodel', verbose_name='Goods'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='inventory_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='inventory.inventorybalance', verbose_name='Inventory Balance'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_lines', to='locations.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='countapproval',
            name='cycle_count_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval', to='counting.cyclecountline', verbose_name='Cycle Count Line'),
        ),
        migrations.AddConstraint(
            model_name='cyclecount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'count_number'), name='count_cycle_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='cyclecountline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('cycle_count', 'line_number'), name='count_line_number_uq'),
        ),
    ]
