# Generated by Django 5.2.12 on 2026-03-13 11:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0002_initial'),
        ('staff', '0002_rename_creater_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclecount',
            name='is_blind_count',
            field=models.BooleanField(default=False, verbose_name='Is Blind Count'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigned At'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cycle_count_lines', to='staff.listmodel', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='recount_assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recount Assigned At'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='recount_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recount_cycle_count_lines', to='staff.listmodel', verbose_name='Recount Assigned To'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='recount_counted_qty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Recounted Qty'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='recounted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Recounted At'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='recounted_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Recounted By'),
        ),
        migrations.AlterField(
            model_name='cyclecount',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COUNTED', 'Counted'), ('RECOUNT_IN_PROGRESS', 'Recount In Progress'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cyclecountline',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COUNTED', 'Counted'), ('RECOUNT_ASSIGNED', 'Recount Assigned'), ('PENDING_APPROVAL', 'Pending Approval'), ('RECONCILED', 'Reconciled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status'),
        ),
    ]
