# Generated by Django 5.2.12 on 2026-03-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0003_cyclecount_is_blind_count_cyclecountline_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyclecountline',
            name='scanner_task_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scanner Task Acknowledged At'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='scanner_task_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scanner Task Completed At'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='scanner_task_last_operator',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Scanner Task Last Operator'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='scanner_task_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scanner Task Started At'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='scanner_task_status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='UNASSIGNED', max_length=16, verbose_name='Scanner Task Status'),
        ),
        migrations.AddField(
            model_name='cyclecountline',
            name='scanner_task_type',
            field=models.CharField(choices=[('NONE', 'None'), ('COUNT', 'Count'), ('RECOUNT', 'Recount')], default='NONE', max_length=16, verbose_name='Scanner Task Type'),
        ),
    ]
