# Generated by Django 5.2.12 on 2026-03-14 00:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outbound', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('system_type', models.CharField(choices=[('ERP', 'ERP'), ('CARRIER', 'Carrier'), ('WEBHOOK', 'Webhook')], max_length=16, verbose_name='System Type')),
                ('integration_name', models.CharField(max_length=64, verbose_name='Integration Name')),
                ('job_type', models.CharField(choices=[('ERP_SYNC', 'ERP Sync'), ('STOCK_EXPORT', 'Stock Export'), ('SHIPMENT_EXPORT', 'Shipment Export'), ('CARRIER_BOOKING', 'Carrier Booking'), ('LABEL_GENERATION', 'Label Generation'), ('WEBHOOK_PROCESSING', 'Webhook Processing')], max_length=32, verbose_name='Job Type')),
                ('direction', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=16, verbose_name='Direction')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16, verbose_name='Status')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('external_reference', models.CharField(blank=True, default='', max_length=128, verbose_name='External Reference')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Request Payload')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Response Payload')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempt Count')),
                ('triggered_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Triggered By')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_jobs', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Integration Job',
                'verbose_name_plural': 'Integration Jobs',
                'db_table': 'integrations_job',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('system_type', models.CharField(choices=[('ERP', 'ERP'), ('CARRIER', 'Carrier'), ('WEBHOOK', 'Webhook')], default='WEBHOOK', max_length=16, verbose_name='System Type')),
                ('source_system', models.CharField(max_length=64, verbose_name='Source System')),
                ('event_type', models.CharField(max_length=128, verbose_name='Event Type')),
                ('event_key', models.CharField(max_length=128, verbose_name='Event Key')),
                ('signature', models.CharField(blank=True, default='', max_length=255, verbose_name='Signature')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Headers')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('QUEUED', 'Queued'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], default='RECEIVED', max_length=16, verbose_name='Status')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Received At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'db_table': 'integrations_webhook_event',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=16, verbose_name='Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Logged At')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='integrations.integrationjob', verbose_name='Integration Job')),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='integrations.webhookevent', verbose_name='Webhook Event')),
            ],
            options={
                'verbose_name': 'Integration Log',
                'verbose_name_plural': 'Integration Logs',
                'db_table': 'integrations_log',
                'ordering': ['-logged_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='integrationjob',
            name='source_webhook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integration_jobs', to='integrations.webhookevent', verbose_name='Source Webhook'),
        ),
        migrations.CreateModel(
            name='CarrierBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('booking_number', models.CharField(max_length=64, verbose_name='Booking Number')),
                ('carrier_code', models.CharField(max_length=64, verbose_name='Carrier Code')),
                ('service_level', models.CharField(blank=True, default='', max_length=64, verbose_name='Service Level')),
                ('package_count', models.PositiveIntegerField(default=1, verbose_name='Package Count')),
                ('total_weight', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Total Weight')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BOOKED', 'Booked'), ('LABELED', 'Labeled'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=16, verbose_name='Status')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=128, verbose_name='Tracking Number')),
                ('label_format', models.CharField(blank=True, default='', max_length=16, verbose_name='Label Format')),
                ('label_document', models.TextField(blank=True, default='', verbose_name='Label Document')),
                ('external_reference', models.CharField(blank=True, default='', max_length=128, verbose_name='External Reference')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Request Payload')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Response Payload')),
                ('booked_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Booked By')),
                ('booked_at', models.DateTimeField(blank=True, null=True, verbose_name='Booked At')),
                ('labeled_at', models.DateTimeField(blank=True, null=True, verbose_name='Labeled At')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carrier_bookings', to='outbound.shipment', verbose_name='Shipment')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_bookings', to='warehouse.warehouse', verbose_name='Warehouse')),
                ('booking_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='integrations.integrationjob', verbose_name='Booking Job')),
                ('label_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labeled_bookings', to='integrations.integrationjob', verbose_name='Label Job')),
            ],
            options={
                'verbose_name': 'Carrier Booking',
                'verbose_name_plural': 'Carrier Bookings',
                'db_table': 'integrations_carrier_booking',
                'ordering': ['-create_time', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'booking_number'), name='integrations_carrier_booking_number_uq')],
            },
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'source_system', 'event_key'), name='integrations_webhook_source_key_uq'),
        ),
    ]
