# Generated by Django 5.2.12 on 2026-03-13 03:47

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_rename_creater_creator'),
        ('goods', '0002_rename_creater_creator'),
        ('inventory', '0001_initial'),
        ('locations', '0001_initial'),
        ('staff', '0002_rename_creater_creator'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('order_number', models.CharField(max_length=64, verbose_name='Sales Order Number')),
                ('requested_ship_date', models.DateField(blank=True, null=True, verbose_name='Requested Ship Date')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ALLOCATED', 'Allocated'), ('PICKING', 'Picking'), ('PICKED', 'Picked'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='customer.listmodel', verbose_name='Customer')),
                ('staging_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='locations.location', verbose_name='Staging Location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'db_table': 'outbound_sales_order',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('line_number', models.PositiveIntegerField(verbose_name='Line Number')),
                ('ordered_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Ordered Qty')),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Allocated Qty')),
                ('picked_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Picked Qty')),
                ('shipped_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Shipped Qty')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Unit Price')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ALLOCATED', 'Allocated'), ('PARTIAL', 'Partial'), ('PICKED', 'Picked'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='goods.listmodel', verbose_name='Goods')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='outbound.salesorder', verbose_name='Sales Order')),
            ],
            options={
                'verbose_name': 'Sales Order Line',
                'verbose_name_plural': 'Sales Order Lines',
                'db_table': 'outbound_sales_order_line',
                'ordering': ['sales_order_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('task_number', models.CharField(max_length=64, verbose_name='Task Number')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('completed_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Completed By')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='staff.listmodel', verbose_name='Assigned To')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks_from', to='locations.location', verbose_name='From Location')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='goods.listmodel', verbose_name='Goods')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_pick_tasks', to='inventory.inventorymovement', verbose_name='Inventory Movement')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks_to', to='locations.location', verbose_name='To Location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='warehouse.warehouse', verbose_name='Warehouse')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='outbound.salesorderline', verbose_name='Sales Order Line')),
            ],
            options={
                'verbose_name': 'Pick Task',
                'verbose_name_plural': 'Pick Tasks',
                'db_table': 'outbound_pick_task',
                'ordering': ['status', 'create_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('shipment_number', models.CharField(max_length=64, verbose_name='Shipment Number')),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=32, verbose_name='Status')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('shipped_by', models.CharField(max_length=255, verbose_name='Shipped By')),
                ('shipped_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Shipped At')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='outbound.salesorder', verbose_name='Sales Order')),
                ('staging_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='locations.location', verbose_name='Staging Location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'db_table': 'outbound_shipment',
                'ordering': ['-shipped_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('shipped_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Shipped Qty')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='locations.location', verbose_name='From Location')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='goods.listmodel', verbose_name='Goods')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='inventory.inventorymovement', verbose_name='Inventory Movement')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='outbound.salesorderline', verbose_name='Sales Order Line')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='outbound.shipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'Shipment Line',
                'verbose_name_plural': 'Shipment Lines',
                'db_table': 'outbound_shipment_line',
                'ordering': ['shipment_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'order_number'), name='outbound_sales_order_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('sales_order', 'line_number'), name='outbound_sales_order_line_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('allocated_qty'), '+', models.F('picked_qty')), '+', models.F('shipped_qty')))), name='outbound_sales_order_progress_lte_ordered'),
        ),
        migrations.AddConstraint(
            model_name='picktask',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'task_number'), name='outbound_pick_task_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'shipment_number'), name='outbound_shipment_number_uq'),
        ),
    ]
