# Generated by Django 5.2.12 on 2026-03-14 02:17

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockLoadVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('verified_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Verified Qty')),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=16, verbose_name='Status')),
                ('trailer_reference', models.CharField(blank=True, default='', max_length=128, verbose_name='Trailer Reference')),
                ('verified_by', models.CharField(max_length=255, verbose_name='Verified By')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verified At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Dock Load Verification',
                'verbose_name_plural': 'Dock Load Verifications',
                'db_table': 'outbound_dock_load_verification',
                'ordering': ['-verified_at', '-id'],
            },
        ),
    ]
