# Generated by Django 5.2.12 on 2026-03-14 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_creater_creator'),
        ('locations', '0001_initial'),
        ('outbound', '0002_dockloadverification'),
        ('scanner', '0002_goodsscanrule_barcodealias_licenseplate'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picktask',
            name='license_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pick_tasks', to='scanner.licenseplate', verbose_name='License Plate'),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='license_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='scanner.licenseplate', verbose_name='License Plate'),
        ),
        migrations.AddField(
            model_name='dockloadverification',
            name='dock_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dock_load_verifications', to='locations.location', verbose_name='Dock Location'),
        ),
        migrations.AddField(
            model_name='dockloadverification',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dock_load_verifications', to='goods.listmodel', verbose_name='Goods'),
        ),
        migrations.AddField(
            model_name='dockloadverification',
            name='license_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dock_load_verifications', to='scanner.licenseplate', verbose_name='License Plate'),
        ),
        migrations.AddField(
            model_name='dockloadverification',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dock_load_verifications', to='outbound.shipment', verbose_name='Shipment'),
        ),
        migrations.AddField(
            model_name='dockloadverification',
            name='shipment_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dock_load_verifications', to='outbound.shipmentline', verbose_name='Shipment Line'),
        ),
        migrations.AddField(
            model_name='dockloadverification',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dock_load_verifications', to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
    ]
