# Generated by Django 5.2.12 on 2026-03-16 00:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_creater_creator'),
        ('locations', '0001_initial'),
        ('outbound', '0003_picktask_license_plate_shipmentline_license_plate_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortPickRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('requested_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Requested Qty')),
                ('picked_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Picked Qty')),
                ('short_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Short Qty')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('reason_code', models.CharField(choices=[('INVENTORY_MISSING', 'Inventory Missing'), ('DAMAGED', 'Damaged'), ('LOCATION_EMPTY', 'Location Empty'), ('LPN_MISMATCH', 'LPN Mismatch'), ('COUNT_REQUIRED', 'Count Required'), ('OTHER', 'Other')], max_length=32, verbose_name='Reason Code')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('reported_by', models.CharField(max_length=255, verbose_name='Reported By')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reported At')),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Resolved By')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_notes', models.TextField(blank=True, default='', verbose_name='Resolution Notes')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_pick_records_from', to='locations.location', verbose_name='From Location')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_pick_records', to='goods.listmodel', verbose_name='Goods')),
                ('pick_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_pick_records', to='outbound.picktask', verbose_name='Pick Task')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_pick_records', to='outbound.salesorder', verbose_name='Sales Order')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_pick_records', to='outbound.salesorderline', verbose_name='Sales Order Line')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='short_pick_records_to', to='locations.location', verbose_name='To Location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_pick_records', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Short Pick Record',
                'verbose_name_plural': 'Short Pick Records',
                'db_table': 'outbound_short_pick_record',
                'ordering': ['status', '-reported_at', '-id'],
            },
        ),
    ]
