# Generated by Django 5.2.12 on 2026-03-21 23:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def _backfill_sales_order_catalog_fields(apps, schema_editor):
    SalesOrder = apps.get_model("outbound", "SalesOrder")
    ShortPickRecord = apps.get_model("outbound", "ShortPickRecord")

    for sales_order in SalesOrder.objects.all().iterator():
        update_fields = []
        if sales_order.order_time is None:
            sales_order.order_time = sales_order.create_time
            update_fields.append("order_time")

        if sales_order.status == "SHIPPED":
            fulfillment_stage = "SHIPPED"
        elif sales_order.status == "CANCELLED":
            fulfillment_stage = "CANCELLED"
        elif sales_order.status in {"ALLOCATED", "PICKING", "PICKED"}:
            fulfillment_stage = "IN_PROCESS"
        else:
            fulfillment_stage = "GET_TRACKING_NO"
        if sales_order.fulfillment_stage != fulfillment_stage:
            sales_order.fulfillment_stage = fulfillment_stage
            update_fields.append("fulfillment_stage")

        has_open_short_pick = ShortPickRecord.objects.filter(
            sales_order_id=sales_order.id,
            is_delete=False,
            status="OPEN",
        ).exists()
        exception_state = "ABNORMAL_PACKAGE" if has_open_short_pick else "NORMAL"
        if sales_order.exception_state != exception_state:
            sales_order.exception_state = exception_state
            update_fields.append("exception_state")

        if update_fields:
            sales_order.save(update_fields=update_fields)


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0004_shortpickrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='deliverer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Deliverer Name'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='deliverer_phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Deliverer Phone'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='exception_notes',
            field=models.TextField(blank=True, default='', verbose_name='Exception Notes'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='exception_state',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL_PACKAGE', 'Abnormal Package'), ('ORDER_INTERCEPTION', 'Order Interception')], default='NORMAL', max_length=32, verbose_name='Exception State'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Time'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='fulfillment_stage',
            field=models.CharField(choices=[('GET_TRACKING_NO', 'Get Tracking No'), ('TO_MOVE', 'To Move'), ('IN_PROCESS', 'In Process Orders'), ('TO_SHIP', 'To Ship'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='GET_TRACKING_NO', max_length=32, verbose_name='Fulfillment Stage'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='logistics_provider',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Logistics Provider'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Order Time'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='package_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Package Count'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='package_height',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Package Height'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='package_length',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Package Length'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='package_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Package Type'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='package_volume',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Package Volume'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='package_weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Package Weight'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='package_width',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Package Width'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Packed At'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='picking_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Picking Completed At'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='picking_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Picking Started At'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='receiver_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Receiver Address'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='receiver_city',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Receiver City'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='receiver_country',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Receiver Country'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='receiver_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Receiver Name'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='receiver_phone',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Receiver Phone'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='receiver_postal_code',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Receiver Postal Code'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='receiver_state',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Receiver State'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipping_method',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Shipping Method'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Tracking Number'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='waybill_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Waybill Number'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='waybill_printed',
            field=models.BooleanField(default=False, verbose_name='Waybill Printed'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='waybill_printed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waybill Printed At'),
        ),
        migrations.RunPython(_backfill_sales_order_catalog_fields, _noop_reverse),
    ]
