# Generated by Django 5.2.12 on 2026-03-22 10:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0005_salesorder_deliverer_name_salesorder_deliverer_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboundWave",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(default="system", max_length=255, verbose_name="Created By")),
                ("openid", models.CharField(db_index=True, max_length=255, verbose_name="Openid")),
                ("is_delete", models.BooleanField(default=False, verbose_name="Delete Label")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="Create Time")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="Update Time")),
                ("wave_number", models.CharField(max_length=64, verbose_name="Wave Number")),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("RELEASED", "Released"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled")], default="OPEN", max_length=16, verbose_name="Status")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                ("generated_by", models.CharField(max_length=255, verbose_name="Generated By")),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Generated At")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="outbound_waves", to="warehouse.warehouse", verbose_name="Warehouse")),
            ],
            options={
                "verbose_name": "Outbound Wave",
                "verbose_name_plural": "Outbound Waves",
                "db_table": "outbound_wave",
                "ordering": ["-generated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LogisticsTrackingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(default="system", max_length=255, verbose_name="Created By")),
                ("openid", models.CharField(db_index=True, max_length=255, verbose_name="Openid")),
                ("is_delete", models.BooleanField(default=False, verbose_name="Delete Label")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="Create Time")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="Update Time")),
                ("event_number", models.CharField(max_length=64, verbose_name="Event Number")),
                ("tracking_number", models.CharField(max_length=64, verbose_name="Tracking Number")),
                ("event_code", models.CharField(max_length=32, verbose_name="Event Code")),
                ("event_status", models.CharField(choices=[("INFO_RECEIVED", "Info Received"), ("IN_TRANSIT", "In Transit"), ("ARRIVED", "Arrived"), ("OUT_FOR_DELIVERY", "Out For Delivery"), ("DELIVERED", "Delivered"), ("EXCEPTION", "Exception")], max_length=32, verbose_name="Event Status")),
                ("event_location", models.CharField(blank=True, default="", max_length=255, verbose_name="Event Location")),
                ("description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Occurred At")),
                ("recorded_by", models.CharField(max_length=255, verbose_name="Recorded By")),
                ("sales_order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tracking_events", to="outbound.salesorder", verbose_name="Sales Order")),
                ("shipment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="tracking_events", to="outbound.shipment", verbose_name="Shipment")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="logistics_tracking_events", to="warehouse.warehouse", verbose_name="Warehouse")),
            ],
            options={
                "verbose_name": "Logistics Tracking Event",
                "verbose_name_plural": "Logistics Tracking Events",
                "db_table": "outbound_logistics_tracking_event",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PackageExecutionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(default="system", max_length=255, verbose_name="Created By")),
                ("openid", models.CharField(db_index=True, max_length=255, verbose_name="Openid")),
                ("is_delete", models.BooleanField(default=False, verbose_name="Delete Label")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="Create Time")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="Update Time")),
                ("record_number", models.CharField(max_length=64, verbose_name="Record Number")),
                ("step_type", models.CharField(choices=[("PACK", "Scan To Pack"), ("INSPECT", "Scan To Inspect"), ("WEIGH", "Weighing To Ship")], max_length=16, verbose_name="Step Type")),
                ("execution_status", models.CharField(choices=[("SUCCESS", "Success"), ("FLAGGED", "Flagged")], default="SUCCESS", max_length=16, verbose_name="Execution Status")),
                ("package_number", models.CharField(max_length=64, verbose_name="Package Number")),
                ("scan_code", models.CharField(blank=True, default="", max_length=255, verbose_name="Scan Code")),
                ("weight", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0.0000"))], verbose_name="Weight")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                ("executed_by", models.CharField(max_length=255, verbose_name="Executed By")),
                ("executed_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Executed At")),
                ("sales_order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="package_execution_records", to="outbound.salesorder", verbose_name="Sales Order")),
                ("shipment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="package_execution_records", to="outbound.shipment", verbose_name="Shipment")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="package_execution_records", to="warehouse.warehouse", verbose_name="Warehouse")),
                ("wave", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="package_execution_records", to="outbound.outboundwave", verbose_name="Wave")),
            ],
            options={
                "verbose_name": "Package Execution Record",
                "verbose_name_plural": "Package Execution Records",
                "db_table": "outbound_package_execution_record",
                "ordering": ["-executed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentDocumentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(default="system", max_length=255, verbose_name="Created By")),
                ("openid", models.CharField(db_index=True, max_length=255, verbose_name="Openid")),
                ("is_delete", models.BooleanField(default=False, verbose_name="Delete Label")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="Create Time")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="Update Time")),
                ("document_number", models.CharField(max_length=64, verbose_name="Document Number")),
                ("document_type", models.CharField(choices=[("MANIFEST", "Manifest Record"), ("PHOTO", "Photo Record"), ("SCANFORM", "Get Scanform")], max_length=16, verbose_name="Document Type")),
                ("reference_code", models.CharField(blank=True, default="", max_length=64, verbose_name="Reference Code")),
                ("file_name", models.CharField(blank=True, default="", max_length=255, verbose_name="File Name")),
                ("notes", models.TextField(blank=True, default="", verbose_name="Notes")),
                ("generated_by", models.CharField(max_length=255, verbose_name="Generated By")),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Generated At")),
                ("sales_order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="shipment_document_records", to="outbound.salesorder", verbose_name="Sales Order")),
                ("shipment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="document_records", to="outbound.shipment", verbose_name="Shipment")),
                ("warehouse", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="shipment_document_records", to="warehouse.warehouse", verbose_name="Warehouse")),
                ("wave", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="document_records", to="outbound.outboundwave", verbose_name="Wave")),
            ],
            options={
                "verbose_name": "Shipment Document Record",
                "verbose_name_plural": "Shipment Document Records",
                "db_table": "outbound_shipment_document_record",
                "ordering": ["-generated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OutboundWaveOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(default="system", max_length=255, verbose_name="Created By")),
                ("openid", models.CharField(db_index=True, max_length=255, verbose_name="Openid")),
                ("is_delete", models.BooleanField(default=False, verbose_name="Delete Label")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="Create Time")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="Update Time")),
                ("sort_sequence", models.PositiveIntegerField(default=1, verbose_name="Sort Sequence")),
                ("sales_order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wave_assignments", to="outbound.salesorder", verbose_name="Sales Order")),
                ("wave", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="outbound.outboundwave", verbose_name="Wave")),
            ],
            options={
                "verbose_name": "Outbound Wave Order",
                "verbose_name_plural": "Outbound Wave Orders",
                "db_table": "outbound_wave_order",
                "ordering": ["wave_id", "sort_sequence", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="outboundwave",
            constraint=models.UniqueConstraint(condition=models.Q(("is_delete", False)), fields=("openid", "wave_number"), name="outbound_wave_number_uq"),
        ),
        migrations.AddConstraint(
            model_name="logisticstrackingevent",
            constraint=models.UniqueConstraint(condition=models.Q(("is_delete", False)), fields=("openid", "event_number"), name="outbound_tracking_event_number_uq"),
        ),
        migrations.AddConstraint(
            model_name="packageexecutionrecord",
            constraint=models.UniqueConstraint(condition=models.Q(("is_delete", False)), fields=("openid", "record_number"), name="outbound_package_execution_number_uq"),
        ),
        migrations.AddConstraint(
            model_name="shipmentdocumentrecord",
            constraint=models.UniqueConstraint(condition=models.Q(("is_delete", False)), fields=("openid", "document_number"), name="outbound_shipment_document_number_uq"),
        ),
        migrations.AddConstraint(
            model_name="outboundwaveorder",
            constraint=models.UniqueConstraint(condition=models.Q(("is_delete", False)), fields=("wave", "sales_order"), name="outbound_wave_order_sales_order_uq"),
        ),
    ]
