# Generated by Django 5.2.12 on 2026-03-22 00:00

from django.db import migrations, models


ORDER_TYPE_CHOICES = [
    ("STANDARD", "Standard"),
    ("B2B", "B2B"),
    ("DROPSHIP", "Dropshipping"),
]


def backfill_wave_order_type(apps, schema_editor):
    OutboundWave = apps.get_model("outbound", "OutboundWave")
    OutboundWaveOrder = apps.get_model("outbound", "OutboundWaveOrder")

    for wave in OutboundWave.objects.all().iterator():
        assignment = (
            OutboundWaveOrder.objects.filter(wave_id=wave.id)
            .select_related("sales_order")
            .order_by("sort_sequence", "id")
            .first()
        )
        wave.order_type = getattr(getattr(assignment, "sales_order", None), "order_type", "DROPSHIP") or "DROPSHIP"
        wave.save(update_fields=["order_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0007_packageexecutionrecord_support_relabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="order_type",
            field=models.CharField(
                choices=ORDER_TYPE_CHOICES,
                default="DROPSHIP",
                max_length=32,
                verbose_name="Order Type",
            ),
        ),
        migrations.AddField(
            model_name="outboundwave",
            name="order_type",
            field=models.CharField(
                choices=ORDER_TYPE_CHOICES,
                default="DROPSHIP",
                max_length=32,
                verbose_name="Order Type",
            ),
        ),
        migrations.RunPython(backfill_wave_order_type, migrations.RunPython.noop),
    ]
