from __future__ import annotations

from decimal import Decimal
from typing import Any

from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from apps.organizations.models import Organization
from apps.warehouse.models import Warehouse


class OperationalReportType(models.TextChoices):
    INVENTORY_AGING = "INVENTORY_AGING", "Inventory Aging"
    RECEIVING_THROUGHPUT = "RECEIVING_THROUGHPUT", "Receiving Throughput"
    SHIPPING_THROUGHPUT = "SHIPPING_THROUGHPUT", "Shipping Throughput"


class OperationalReportStatus(models.TextChoices):
    GENERATED = "GENERATED", "Generated"
    EXPIRED = "EXPIRED", "Expired"


class WarehouseKpiSnapshot(models.Model):
    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        related_name="warehouse_kpi_snapshots",
    )
    warehouse = models.ForeignKey(
        Warehouse,
        on_delete=models.CASCADE,
        related_name="kpi_snapshots",
    )
    snapshot_date = models.DateField()
    generated_at = models.DateTimeField(default=timezone.now)
    generated_by = models.CharField(max_length=255)
    on_hand_qty = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"))
    available_qty = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"))
    allocated_qty = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"))
    hold_qty = models.DecimalField(max_digits=18, decimal_places=4, default=Decimal("0.0000"))
    open_purchase_orders = models.PositiveIntegerField(default=0)
    open_sales_orders = models.PositiveIntegerField(default=0)
    open_putaway_tasks = models.PositiveIntegerField(default=0)
    open_pick_tasks = models.PositiveIntegerField(default=0)
    pending_count_approvals = models.PositiveIntegerField(default=0)
    pending_return_orders = models.PositiveIntegerField(default=0)
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("organization_id", "-snapshot_date", "-id")
        constraints = [
            models.UniqueConstraint(
                fields=("organization", "warehouse", "snapshot_date"),
                name="unique_reporting_kpi_snapshot_per_day",
            ),
        ]
        permissions = [
            ("view_reporting", "Can view reporting"),
            ("manage_reporting", "Can manage reporting"),
        ]

    def clean(self) -> None:
        super().clean()
        self.generated_by = self.generated_by.strip()
        errors: dict[str, str] = {}
        if not self.generated_by:
            errors["generated_by"] = "Generated by cannot be blank."
        if self.warehouse.organization_id != self.organization_id:
            errors["warehouse"] = "Warehouse must belong to the same organization as the KPI snapshot."
        if errors:
            raise ValidationError(errors)

    def save(self, *args: Any, **kwargs: Any) -> None:
        self.full_clean()
        super().save(*args, **kwargs)


class OperationalReportExport(models.Model):
    organization = models.ForeignKey(
        Organization,
        on_delete=models.CASCADE,
        related_name="operational_report_exports",
    )
    warehouse = models.ForeignKey(
        Warehouse,
        on_delete=models.CASCADE,
        related_name="report_exports",
        blank=True,
        null=True,
    )
    report_type = models.CharField(max_length=32, choices=OperationalReportType.choices)
    status = models.CharField(
        max_length=16,
        choices=OperationalReportStatus.choices,
        default=OperationalReportStatus.GENERATED,
    )
    export_format = models.CharField(max_length=16, default="csv")
    date_from = models.DateField(blank=True, null=True)
    date_to = models.DateField(blank=True, null=True)
    parameters = models.JSONField(default=dict, blank=True)
    file_name = models.CharField(max_length=255)
    row_count = models.PositiveIntegerField(default=0)
    generated_at = models.DateTimeField(default=timezone.now)
    generated_by = models.CharField(max_length=255)
    content = models.TextField(blank=True, default="")
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("organization_id", "-generated_at", "-id")

    def clean(self) -> None:
        super().clean()
        self.export_format = self.export_format.strip().lower() or "csv"
        self.file_name = self.file_name.strip()
        self.generated_by = self.generated_by.strip()
        errors: dict[str, str] = {}
        if self.warehouse is not None and self.warehouse.organization_id != self.organization_id:
            errors["warehouse"] = "Warehouse must belong to the same organization as the report export."
        if self.export_format != "csv":
            errors["export_format"] = "Only csv exports are supported."
        if not self.file_name:
            errors["file_name"] = "File name cannot be blank."
        if not self.generated_by:
            errors["generated_by"] = "Generated by cannot be blank."
        if self.date_from is not None and self.date_to is not None and self.date_from > self.date_to:
            errors["date_from"] = "date_from cannot be after date_to."
        if errors:
            raise ValidationError(errors)

    def save(self, *args: Any, **kwargs: Any) -> None:
        self.full_clean()
        super().save(*args, **kwargs)

