import Grid from "@mui/material/Grid";
import { Stack } from "@mui/material";

import { useReportingController } from "@/features/reporting/controller/useReportingController";
import { FinanceTable } from "@/features/reporting/view/FinanceTable";
import { PageHeader } from "@/shared/components/page-header";
import { ResourceTable } from "@/shared/components/resource-table";
import { StatusChip } from "@/shared/components/status-chip";
import { formatDateTime, formatNumber } from "@/shared/utils/format";
import { parseApiError } from "@/shared/utils/parse-api-error";

export function FinancePage() {
  const { disputesQuery, exportsQuery, invoicesQuery, settlementsQuery } = useReportingController();

  return (
    <Stack spacing={3}>
      <PageHeader
        description="Finance review surface for invoices, settlements, disputes, and exported remittance packs."
        title="Finance"
      />
      <Grid container spacing={2.5}>
        <Grid size={{ xs: 12 }}>
          <FinanceTable
            error={invoicesQuery.error ? parseApiError(invoicesQuery.error) : null}
            isLoading={invoicesQuery.isLoading}
            rows={invoicesQuery.data?.results ?? []}
          />
        </Grid>
        <Grid size={{ xs: 12, xl: 6 }}>
          <ResourceTable
            columns={[
              { header: "Settlement", key: "settlement", render: (row) => row.settlement_reference },
              { header: "Requested", key: "requested", align: "right", render: (row) => formatNumber(row.requested_amount) },
              { header: "Approved", key: "approved", align: "right", render: (row) => formatNumber(row.approved_amount) },
              { header: "Remitted", key: "remitted", align: "right", render: (row) => formatNumber(row.remitted_amount) },
              { header: "Status", key: "status", render: (row) => <StatusChip status={row.status} /> },
            ]}
            error={settlementsQuery.error ? parseApiError(settlementsQuery.error) : null}
            getRowId={(row) => row.id}
            isLoading={settlementsQuery.isLoading}
            rows={settlementsQuery.data?.results ?? []}
            subtitle="Settlement and remittance workflow"
            title="Settlements"
          />
        </Grid>
        <Grid size={{ xs: 12, xl: 6 }}>
          <ResourceTable
            columns={[
              { header: "Reference", key: "reference", render: (row) => row.dispute_reference },
              { header: "Amount", key: "amount", align: "right", render: (row) => formatNumber(row.disputed_amount) },
              { header: "Reason", key: "reason", render: (row) => row.reason_code },
              { header: "Submitted", key: "submitted", render: (row) => formatDateTime(row.submitted_at) },
              { header: "Status", key: "status", render: (row) => <StatusChip status={row.status} /> },
            ]}
            error={disputesQuery.error ? parseApiError(disputesQuery.error) : null}
            getRowId={(row) => row.id}
            isLoading={disputesQuery.isLoading}
            rows={disputesQuery.data?.results ?? []}
            subtitle="Open and recently resolved invoice disputes"
            title="Disputes"
          />
        </Grid>
        <Grid size={{ xs: 12 }}>
          <ResourceTable
            columns={[
              { header: "Export", key: "export", render: (row) => row.file_name || `finance-export-${row.id}.csv` },
              { header: "Rows", key: "rows", align: "right", render: (row) => formatNumber(row.row_count) },
              { header: "Generated at", key: "generatedAt", render: (row) => formatDateTime(row.generated_at) },
              { header: "Generated by", key: "generatedBy", render: (row) => row.generated_by || "--" },
              { header: "Status", key: "status", render: (row) => <StatusChip status={row.status} /> },
            ]}
            error={exportsQuery.error ? parseApiError(exportsQuery.error) : null}
            getRowId={(row) => row.id}
            isLoading={exportsQuery.isLoading}
            rows={exportsQuery.data?.results ?? []}
            subtitle="Latest finance export runs ready for downstream accounting"
            title="Finance exports"
          />
        </Grid>
      </Grid>
    </Stack>
  );
}
