import { useMemo } from "react";

import { zodResolver } from "@hookform/resolvers/zod";
import { Button, Grid, Stack } from "@mui/material";
import { useForm } from "react-hook-form";
import { Link as RouterLink, Navigate, useParams } from "react-router-dom";

import { useInvoiceDetailController } from "@/features/reporting/controller/useReportingController";
import { sumInvoiceAmounts } from "@/features/reporting/model/mappers";
import type { InvoiceActionValues } from "@/features/reporting/model/types";
import { invoiceActionSchema } from "@/features/reporting/model/validators";
import { FinanceForm } from "@/features/reporting/view/FinanceForm";
import { RouteFallback } from "@/shared/components/route-fallback";
import { DetailCard } from "@/shared/components/detail-card";
import { DetailGrid } from "@/shared/components/detail-grid";
import { PageHeader } from "@/shared/components/page-header";
import { QueryAlert } from "@/shared/components/query-alert";
import { ResourceTable } from "@/shared/components/resource-table";
import { StatusChip } from "@/shared/components/status-chip";
import { formatDateTime, formatNumber } from "@/shared/utils/format";
import { parseApiError } from "@/shared/utils/parse-api-error";

export function InvoiceDetailPage() {
  const { invoiceId } = useParams<{ invoiceId: string }>();
  const { actionMutation, defaultValues, errorMessage, invoiceQuery, successMessage } =
    useInvoiceDetailController(invoiceId);

  const form = useForm<InvoiceActionValues>({
    defaultValues,
    resolver: zodResolver(invoiceActionSchema),
  });

  const summaryItems = useMemo(() => {
    if (!invoiceQuery.data) {
      return [];
    }
    const invoice = invoiceQuery.data;
    return [
      { label: "Invoice number", value: invoice.invoice_number },
      { label: "Status", value: <StatusChip status={invoice.status} /> },
      { label: "Period start", value: formatDateTime(invoice.period_start) },
      { label: "Period end", value: formatDateTime(invoice.period_end) },
      { label: "Subtotal", value: `${formatNumber(invoice.subtotal_amount)} ${invoice.currency}` },
      { label: "Tax", value: `${formatNumber(invoice.tax_amount)} ${invoice.currency}` },
      { label: "Total", value: `${formatNumber(invoice.total_amount)} ${invoice.currency}` },
      {
        label: "Disputed",
        value: `${formatNumber(invoice.disputed_amount ?? sumInvoiceAmounts(invoice.disputes ?? [], "disputed_amount"))} ${invoice.currency}`,
      },
      {
        label: "Credited",
        value: `${formatNumber(invoice.credited_amount ?? sumInvoiceAmounts(invoice.credit_notes ?? [], "amount"))} ${invoice.currency}`,
      },
      { label: "Generated by", value: invoice.generated_by || "--" },
      { label: "Generated at", value: formatDateTime(invoice.generated_at) },
      { label: "Finalized at", value: formatDateTime(invoice.finalized_at) },
    ];
  }, [invoiceQuery.data]);

  const financeItems = useMemo(() => {
    if (!invoiceQuery.data) {
      return [];
    }
    const approval = invoiceQuery.data.finance_approval;
    const settlement = invoiceQuery.data.settlement;
    return [
      { label: "Finance status", value: approval ? <StatusChip status={approval.status} /> : "--" },
      { label: "Submitted by", value: approval?.submitted_by || "--" },
      { label: "Submitted at", value: formatDateTime(approval?.submitted_at) },
      { label: "Reviewed by", value: approval?.reviewed_by || "--" },
      { label: "Reviewed at", value: formatDateTime(approval?.reviewed_at) },
      { label: "Settlement status", value: settlement ? <StatusChip status={settlement.status} /> : "--" },
      { label: "Settlement reference", value: settlement?.settlement_reference || "--" },
      {
        label: "Remitted",
        value: settlement ? `${formatNumber(settlement.remitted_amount)} ${settlement.currency}` : "--",
      },
      { label: "Finance notes", value: approval?.notes || invoiceQuery.data.notes || "--" },
    ];
  }, [invoiceQuery.data]);

  if (!invoiceId) {
    return <Navigate replace to="/finance" />;
  }

  if (invoiceQuery.isLoading) {
    return <RouteFallback />;
  }

  const invoice = invoiceQuery.data;
  const canFinalize = invoice?.status === "DRAFT";
  const financeStatus = invoice?.finance_approval?.status ?? null;
  const canSubmitFinanceReview =
    invoice?.status === "FINALIZED" && (financeStatus === null || financeStatus === "REJECTED");
  const canDecideFinanceReview = financeStatus === "PENDING";

  return (
    <Stack spacing={3}>
      <PageHeader
        actions={
          <Button component={RouterLink} to="/finance" variant="outlined">
            Back to finance
          </Button>
        }
        description="Inspect invoice lines, finance state, settlement context, and drive the finance review workflow from one screen."
        title="Invoice detail"
      />
      <QueryAlert message={invoiceQuery.error ? parseApiError(invoiceQuery.error) : null} />
      <QueryAlert message={errorMessage} />
      {!invoice ? null : (
        <>
          <DetailCard description="Commercial header and total values returned by the reporting API." title="Invoice summary">
            <DetailGrid items={summaryItems} />
          </DetailCard>
          <DetailCard description="Finance review and settlement status for the current invoice." title="Finance state">
            <DetailGrid items={financeItems} />
          </DetailCard>
          <DetailCard description="Each button maps directly to the matching backend finance endpoint." title="Invoice actions">
            <FinanceForm
              canDecideFinanceReview={canDecideFinanceReview}
              canFinalize={canFinalize}
              canSubmitFinanceReview={canSubmitFinanceReview}
              form={form}
              isSubmitting={actionMutation.isPending}
              onApproveFinanceReview={form.handleSubmit((values) =>
                actionMutation.mutate({ action: "approve-finance-review", values }),
              )}
              onFinalize={form.handleSubmit((values) => actionMutation.mutate({ action: "finalize", values }))}
              onRejectFinanceReview={form.handleSubmit((values) =>
                actionMutation.mutate({ action: "reject-finance-review", values }),
              )}
              onSubmitFinanceReview={form.handleSubmit((values) =>
                actionMutation.mutate({ action: "submit-finance-review", values }),
              )}
              successMessage={successMessage}
            />
          </DetailCard>
          <ResourceTable
            columns={[
              { header: "Line", key: "line", render: (row) => row.id },
              { header: "Charge type", key: "chargeType", render: (row) => row.charge_type },
              { header: "Event date", key: "eventDate", render: (row) => formatDateTime(row.event_date) },
              { header: "Qty", key: "quantity", align: "right", render: (row) => formatNumber(row.quantity) },
              { header: "Rate", key: "rate", align: "right", render: (row) => formatNumber(row.unit_rate) },
              { header: "Amount", key: "amount", align: "right", render: (row) => formatNumber(row.amount) },
              { header: "Reference", key: "reference", render: (row) => row.reference_code || "--" },
            ]}
            getRowId={(row) => row.id}
            rows={invoice.lines ?? []}
            subtitle="Rated billing events that make up the invoice total."
            title="Invoice lines"
          />
          <Grid container spacing={2.5}>
            <Grid size={{ xs: 12, xl: 6 }}>
              <ResourceTable
                columns={[
                  { header: "Reference", key: "reference", render: (row) => row.reference_code || row.dispute_reference || `Dispute ${row.id}` },
                  { header: "Reason", key: "reason", render: (row) => row.reason_code },
                  { header: "Amount", key: "amount", align: "right", render: (row) => formatNumber(row.disputed_amount) },
                  { header: "Status", key: "status", render: (row) => <StatusChip status={row.status} /> },
                ]}
                getRowId={(row) => row.id}
                rows={invoice.disputes ?? []}
                subtitle="Current dispute positions attached to this invoice."
                title="Disputes"
              />
            </Grid>
            <Grid size={{ xs: 12, xl: 6 }}>
              <ResourceTable
                columns={[
                  { header: "Credit note", key: "creditNote", render: (row) => row.credit_note_number },
                  { header: "Reason", key: "reason", render: (row) => row.reason_code },
                  { header: "Amount", key: "amount", align: "right", render: (row) => formatNumber(row.amount) },
                  { header: "Status", key: "status", render: (row) => <StatusChip status={row.status} /> },
                ]}
                getRowId={(row) => row.id}
                rows={invoice.credit_notes ?? []}
                subtitle="Issued and applied credits tied back to this invoice."
                title="Credit notes"
              />
            </Grid>
          </Grid>
        </>
      )}
    </Stack>
  );
}
