# Generated by Django 5.2.12 on 2026-03-14 01:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_rename_creater_creator'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('task_type', models.CharField(choices=[('PROCESS_INTEGRATION_JOB', 'Process Integration Job'), ('GENERATE_KPI_SNAPSHOT', 'Generate KPI Snapshot'), ('GENERATE_OPERATIONAL_REPORT', 'Generate Operational Report'), ('GENERATE_INVOICE', 'Generate Invoice')], max_length=32, verbose_name='Task Type')),
                ('interval_minutes', models.PositiveIntegerField(default=1440, verbose_name='Interval Minutes')),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Next Run At')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Max Attempts')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('last_enqueued_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Enqueued At')),
                ('last_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Completed At')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
                'db_table': 'automation_scheduled_task',
                'ordering': ['next_run_at', 'priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('task_type', models.CharField(choices=[('PROCESS_INTEGRATION_JOB', 'Process Integration Job'), ('GENERATE_KPI_SNAPSHOT', 'Generate KPI Snapshot'), ('GENERATE_OPERATIONAL_REPORT', 'Generate Operational Report'), ('GENERATE_INVOICE', 'Generate Invoice')], max_length=32, verbose_name='Task Type')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('RETRY', 'Retry Scheduled'), ('DEAD', 'Dead')], default='QUEUED', max_length=16, verbose_name='Status')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Available At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempt Count')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='Max Attempts')),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=60, verbose_name='Retry Backoff Seconds')),
                ('locked_by', models.CharField(blank=True, default='', max_length=128, verbose_name='Locked By')),
                ('reference_code', models.CharField(blank=True, default='', max_length=128, verbose_name='Reference Code')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='Result Summary')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_tasks', to='customer.listmodel', verbose_name='Customer')),
                ('integration_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_tasks', to='integrations.integrationjob', verbose_name='Integration Job')),
            ],
            options={
                'verbose_name': 'Background Task',
                'verbose_name_plural': 'Background Tasks',
                'db_table': 'automation_background_task',
                'ordering': ['priority', 'available_at', 'id'],
            },
        ),
    ]
