# Generated by Django 5.2.12 on 2026-03-14 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('customer', '0002_rename_creater_creator'),
        ('reporting', '0002_billingchargeevent_rated_at_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundtask',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_tasks', to='reporting.invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='backgroundtask',
            name='report_export',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_tasks', to='reporting.operationalreportexport', verbose_name='Report Export'),
        ),
        migrations.AddField(
            model_name='backgroundtask',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='background_tasks', to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_tasks', to='customer.listmodel', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_tasks', to='warehouse.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AddField(
            model_name='backgroundtask',
            name='scheduled_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_runs', to='automation.scheduledtask', verbose_name='Scheduled Task'),
        ),
        migrations.AddConstraint(
            model_name='scheduledtask',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'name'), name='automation_schedule_name_uq'),
        ),
    ]
