# Generated by Django 5.2.12 on 2026-03-14 02:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=128, unique=True, verbose_name='Worker Name')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Seen At')),
                ('last_run_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Run Started At')),
                ('last_run_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Run Completed At')),
                ('processed_count', models.PositiveIntegerField(default=0, verbose_name='Processed Count')),
                ('queue_depth', models.PositiveIntegerField(default=0, verbose_name='Queue Depth')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
            ],
            options={
                'verbose_name': 'Worker Heartbeat',
                'verbose_name_plural': 'Worker Heartbeats',
                'db_table': 'automation_worker_heartbeat',
                'ordering': ['worker_name'],
            },
        ),
        migrations.AlterField(
            model_name='backgroundtask',
            name='task_type',
            field=models.CharField(choices=[('PROCESS_INTEGRATION_JOB', 'Process Integration Job'), ('GENERATE_KPI_SNAPSHOT', 'Generate KPI Snapshot'), ('GENERATE_OPERATIONAL_REPORT', 'Generate Operational Report'), ('GENERATE_STORAGE_ACCRUAL', 'Generate Storage Accrual'), ('GENERATE_INVOICE', 'Generate Invoice'), ('GENERATE_FINANCE_EXPORT', 'Generate Finance Export')], max_length=32, verbose_name='Task Type'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('PROCESS_INTEGRATION_JOB', 'Process Integration Job'), ('GENERATE_KPI_SNAPSHOT', 'Generate KPI Snapshot'), ('GENERATE_OPERATIONAL_REPORT', 'Generate Operational Report'), ('GENERATE_STORAGE_ACCRUAL', 'Generate Storage Accrual'), ('GENERATE_INVOICE', 'Generate Invoice'), ('GENERATE_FINANCE_EXPORT', 'Generate Finance Export')], max_length=32, verbose_name='Task Type'),
        ),
        migrations.CreateModel(
            name='AutomationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('alert_type', models.CharField(choices=[('DEAD_TASK', 'Dead Task'), ('RETRY_BACKLOG', 'Retry Backlog'), ('STALE_WORKER', 'Stale Worker')], max_length=32, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=16, verbose_name='Severity')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16, verbose_name='Status')),
                ('alert_key', models.CharField(max_length=255, verbose_name='Alert Key')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opened At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Resolved By')),
                ('background_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_alerts', to='automation.backgroundtask', verbose_name='Background Task')),
                ('scheduled_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_alerts', to='automation.scheduledtask', verbose_name='Scheduled Task')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automation_alerts', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Automation Alert',
                'verbose_name_plural': 'Automation Alerts',
                'db_table': 'automation_alert',
                'ordering': ['-opened_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False), ('status', 'OPEN')), fields=('openid', 'alert_type', 'alert_key', 'status'), name='automation_open_alert_unique')],
            },
        ),
    ]
