# Generated by Django 5.2.12 on 2026-03-16 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_rename_creater_creator'),
        ('userprofile', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_code', models.CharField(max_length=64, verbose_name='Company Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16, verbose_name='Status')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='warehouse.warehouse', verbose_name='Default Warehouse')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'access_company',
                'ordering': ['company_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('is_company_admin', models.BooleanField(default=False, verbose_name='Company Admin')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Can Manage Users')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('invited_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Invited By')),
                ('last_selected_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Selected At')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Auth User')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='access.company', verbose_name='Company')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_memberships', to='warehouse.warehouse', verbose_name='Default Warehouse')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_memberships', to='userprofile.users', verbose_name='Profile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_memberships', to='staff.listmodel', verbose_name='Staff')),
            ],
            options={
                'verbose_name': 'Company Membership',
                'verbose_name_plural': 'Company Memberships',
                'db_table': 'access_company_membership',
                'ordering': ['company_id', 'auth_user_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid',), name='access_company_openid_uq'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('company_code',), name='access_company_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('company', 'auth_user'), name='access_company_auth_user_uq'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('profile',), name='access_company_profile_uq'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('staff',), name='access_company_staff_uq'),
        ),
    ]
