# Generated by Django 5.2.12 on 2026-03-16 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('staff_name', models.CharField(max_length=80, verbose_name='Staff Name')),
                ('staff_type', models.CharField(max_length=255, verbose_name='Staff Type')),
                ('check_code', models.PositiveIntegerField(verbose_name='Check Code')),
                ('is_company_admin', models.BooleanField(default=False, verbose_name='Company Admin')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Can Manage Users')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16, verbose_name='Status')),
                ('invite_token', models.CharField(db_index=True, max_length=128, verbose_name='Invite Token')),
                ('invite_message', models.TextField(blank=True, default='', verbose_name='Invite Message')),
                ('invited_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Invited By')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('accepted_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_invites', to='access.companymembership', verbose_name='Accepted Membership')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites', to='access.company', verbose_name='Company')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_invites', to='warehouse.warehouse', verbose_name='Default Warehouse')),
            ],
            options={
                'verbose_name': 'Company Invite',
                'verbose_name_plural': 'Company Invites',
                'db_table': 'access_company_invite',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('reset_token', models.CharField(db_index=True, max_length=128, verbose_name='Reset Token')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16, verbose_name='Status')),
                ('issued_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Issued By')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_resets', to='access.company', verbose_name='Company')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='password_resets', to='access.companymembership', verbose_name='Membership')),
            ],
            options={
                'verbose_name': 'Company Password Reset',
                'verbose_name_plural': 'Company Password Resets',
                'db_table': 'access_company_password_reset',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccessAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('action_type', models.CharField(choices=[('MEMBERSHIP_PROVISIONED', 'Membership Provisioned'), ('MEMBERSHIP_UPDATED', 'Membership Updated'), ('MEMBERSHIP_SWITCHED', 'Membership Switched'), ('INVITE_CREATED', 'Invite Created'), ('INVITE_REVOKED', 'Invite Revoked'), ('INVITE_ACCEPTED', 'Invite Accepted'), ('PASSWORD_RESET_ISSUED', 'Password Reset Issued'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PASSWORD_RESET_REVOKED', 'Password Reset Revoked')], max_length=64, verbose_name='Action Type')),
                ('actor_name', models.CharField(max_length=255, verbose_name='Actor Name')),
                ('target_identifier', models.CharField(blank=True, default='', max_length=255, verbose_name='Target Identifier')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Occurred At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='access.company', verbose_name='Company')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='access.companymembership', verbose_name='Membership')),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='access.companyinvite', verbose_name='Invite')),
                ('password_reset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='access.companypasswordreset', verbose_name='Password Reset')),
            ],
            options={
                'verbose_name': 'Access Audit Event',
                'verbose_name_plural': 'Access Audit Events',
                'db_table': 'access_audit_event',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='companyinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('invite_token',), name='access_company_invite_token_uq'),
        ),
        migrations.AddConstraint(
            model_name='companypasswordreset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('reset_token',), name='access_password_reset_token_uq'),
        ),
    ]
