# Generated by Django 5.2.12 on 2026-03-16 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_companyinvite_companypasswordreset_accessauditevent_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueViewPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('route_key', models.CharField(max_length=128, verbose_name='Route Key')),
                ('name', models.CharField(max_length=120, verbose_name='View Name')),
                ('search_scope', models.CharField(blank=True, default='', max_length=64, verbose_name='Search Scope')),
                ('status_bucket', models.CharField(blank=True, default='', max_length=64, verbose_name='Status Bucket')),
                ('filter_payload', models.JSONField(blank=True, default=dict, verbose_name='Filter Payload')),
                ('sort_payload', models.JSONField(blank=True, default=dict, verbose_name='Sort Payload')),
                ('visible_columns', models.JSONField(blank=True, default=list, verbose_name='Visible Columns')),
                ('page_size', models.PositiveIntegerField(default=25, verbose_name='Page Size')),
                ('density', models.CharField(choices=[('COMPACT', 'Compact'), ('COMFORTABLE', 'Comfortable')], default='COMPACT', max_length=16, verbose_name='Density')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_view_preferences', to='access.companymembership', verbose_name='Membership')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue_view_preferences', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Queue View Preference',
                'verbose_name_plural': 'Queue View Preferences',
                'db_table': 'access_queue_view_preference',
                'ordering': ['route_key', 'name', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('membership', 'route_key', 'name'), name='access_queue_view_preference_name_uq')],
            },
        ),
        migrations.CreateModel(
            name='WorkbenchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('page_key', models.CharField(max_length=128, verbose_name='Page Key')),
                ('time_window', models.CharField(choices=[('WEEK', 'This Week'), ('MONTH', 'This Month'), ('YEAR', 'This Year')], default='WEEK', max_length=16, verbose_name='Time Window')),
                ('visible_widget_keys', models.JSONField(blank=True, default=list, verbose_name='Visible Widget Keys')),
                ('right_rail_widget_keys', models.JSONField(blank=True, default=list, verbose_name='Right Rail Widget Keys')),
                ('layout_payload', models.JSONField(blank=True, default=dict, verbose_name='Layout Payload')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workbench_preferences', to='access.companymembership', verbose_name='Membership')),
            ],
            options={
                'verbose_name': 'Workbench Preference',
                'verbose_name_plural': 'Workbench Preferences',
                'db_table': 'access_workbench_preference',
                'ordering': ['page_key', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('membership', 'page_key'), name='access_workbench_preference_page_uq')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceTabPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('route_key', models.CharField(max_length=128, verbose_name='Route Key')),
                ('route_path', models.CharField(max_length=255, verbose_name='Route Path')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('icon_key', models.CharField(blank=True, default='', max_length=64, verbose_name='Icon Key')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Is Pinned')),
                ('state_payload', models.JSONField(blank=True, default=dict, verbose_name='State Payload')),
                ('context_payload', models.JSONField(blank=True, default=dict, verbose_name='Context Payload')),
                ('last_opened_at', models.DateTimeField(auto_now=True, verbose_name='Last Opened At')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspace_tab_preferences', to='access.companymembership', verbose_name='Membership')),
            ],
            options={
                'verbose_name': 'Workspace Tab Preference',
                'verbose_name_plural': 'Workspace Tab Preferences',
                'db_table': 'access_workspace_tab_preference',
                'ordering': ['position', '-last_opened_at', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('membership', 'route_path'), name='access_workspace_tab_preference_path_uq')],
            },
        ),
    ]
