# Generated by Django 5.2.12 on 2026-03-13 00:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('type_code', models.CharField(max_length=64, verbose_name='Location Type Code')),
                ('type_name', models.CharField(max_length=255, verbose_name='Location Type Name')),
                ('picking_enabled', models.BooleanField(default=True, verbose_name='Picking Enabled')),
                ('putaway_enabled', models.BooleanField(default=True, verbose_name='Putaway Enabled')),
                ('allow_mixed_sku', models.BooleanField(default=False, verbose_name='Allow Mixed SKU')),
                ('max_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Max Weight')),
                ('max_volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Max Volume')),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
                'db_table': 'location_type',
                'ordering': ['type_code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'type_code'), name='loc_type_code_uq')],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('zone_code', models.CharField(max_length=64, verbose_name='Zone Code')),
                ('zone_name', models.CharField(max_length=255, verbose_name='Zone Name')),
                ('usage', models.CharField(choices=[('RECEIVING', 'Receiving'), ('STORAGE', 'Storage'), ('PICKING', 'Picking'), ('SHIPPING', 'Shipping'), ('QUARANTINE', 'Quarantine'), ('RETURNS', 'Returns')], default='STORAGE', max_length=32, verbose_name='Zone Usage')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Sequence')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'location_zone',
                'ordering': ['warehouse_id', 'sequence', 'zone_code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('location_code', models.CharField(max_length=64, verbose_name='Location Code')),
                ('location_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Location Name')),
                ('aisle', models.CharField(blank=True, default='', max_length=64, verbose_name='Aisle')),
                ('bay', models.CharField(blank=True, default='', max_length=64, verbose_name='Bay')),
                ('level', models.CharField(blank=True, default='', max_length=64, verbose_name='Level')),
                ('slot', models.CharField(blank=True, default='', max_length=64, verbose_name='Slot')),
                ('barcode', models.CharField(blank=True, default='', max_length=255, verbose_name='Barcode')),
                ('capacity_qty', models.PositiveIntegerField(default=0, verbose_name='Capacity Qty')),
                ('max_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Max Weight')),
                ('max_volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Max Volume')),
                ('pick_sequence', models.PositiveIntegerField(default=0, verbose_name='Pick Sequence')),
                ('is_pick_face', models.BooleanField(default=False, verbose_name='Is Pick Face')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Is Locked')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=32, verbose_name='Status')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='warehouse.warehouse', verbose_name='Warehouse')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='locations.locationtype', verbose_name='Location Type')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='locations.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'location',
                'ordering': ['warehouse_id', 'zone_id', 'pick_sequence', 'location_code'],
            },
        ),
        migrations.CreateModel(
            name='LocationLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('reason', models.CharField(max_length=255, verbose_name='Lock Reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('locked_by', models.CharField(max_length=255, verbose_name='Locked By')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locks', to='locations.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Location Lock',
                'verbose_name_plural': 'Location Locks',
                'db_table': 'location_lock',
                'ordering': ['-start_time', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_delete', False)), fields=('location',), name='loc_lock_one_active_uq')],
            },
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'warehouse', 'zone_code'), name='loc_zone_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'warehouse', 'zone_name'), name='loc_zone_name_uq'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'warehouse', 'location_code'), name='loc_code_uq'),
        ),
    ]
