# Generated by Django 5.2.12 on 2026-03-13 00:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_rename_creater_creator'),
        ('locations', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('on_hand_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='On Hand Qty')),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Allocated Qty')),
                ('hold_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Hold Qty')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Unit Cost')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Currency')),
                ('last_movement_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Movement At')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='goods.listmodel', verbose_name='Goods')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='locations.location', verbose_name='Location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Balance',
                'verbose_name_plural': 'Inventory Balances',
                'db_table': 'inventory_balance',
                'ordering': ['warehouse_id', 'location_id', 'goods_id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('held_by', models.CharField(max_length=255, verbose_name='Held By')),
                ('released_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Released By')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Released At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('inventory_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='inventory.inventorybalance', verbose_name='Inventory Balance')),
            ],
            options={
                'verbose_name': 'Inventory Hold',
                'verbose_name_plural': 'Inventory Holds',
                'db_table': 'inventory_hold',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('RECEIPT', 'Receipt'), ('PUTAWAY', 'Putaway'), ('TRANSFER', 'Transfer'), ('PICK', 'Pick'), ('SHIP', 'Ship'), ('ADJUSTMENT_IN', 'Adjustment In'), ('ADJUSTMENT_OUT', 'Adjustment Out'), ('HOLD', 'Hold'), ('RELEASE_HOLD', 'Release Hold')], max_length=32, verbose_name='Movement Type')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Unit Cost')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Reason')),
                ('performed_by', models.CharField(max_length=255, verbose_name='Performed By')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Occurred At')),
                ('resulting_from_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Resulting From Qty')),
                ('resulting_to_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Resulting To Qty')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_out', to='locations.location', verbose_name='From Location')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='goods.listmodel', verbose_name='Goods')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements_in', to='locations.location', verbose_name='To Location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'db_table': 'inventory_movement',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'location', 'goods', 'lot_number', 'serial_number', 'stock_status'), name='inv_balance_uq'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_qty__gte', models.F('allocated_qty'))), name='inv_on_hand_gte_alloc'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_qty__gte', models.F('hold_qty'))), name='inv_on_hand_gte_hold'),
        ),
    ]
