# Generated by Django 5.2.12 on 2026-03-13 10:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('code', models.CharField(max_length=64, verbose_name='Reason Code')),
                ('name', models.CharField(max_length=255, verbose_name='Reason Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('direction', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease'), ('BOTH', 'Both')], default='BOTH', max_length=32, verbose_name='Allowed Direction')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Inventory Adjustment Reason',
                'verbose_name_plural': 'Inventory Adjustment Reasons',
                'db_table': 'inventory_adjustment_reason',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'code'), name='inv_adjust_reason_code_uq')],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('minimum_variance_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Minimum Variance Qty')),
                ('approver_role', models.CharField(max_length=255, verbose_name='Approver Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_approval_rules', to='warehouse.warehouse', verbose_name='Warehouse')),
                ('adjustment_reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules', to='inventory.inventoryadjustmentreason', verbose_name='Adjustment Reason')),
            ],
            options={
                'verbose_name': 'Inventory Adjustment Approval Rule',
                'verbose_name_plural': 'Inventory Adjustment Approval Rules',
                'db_table': 'inventory_adjustment_approval_rule',
                'ordering': ['adjustment_reason_id', '-minimum_variance_qty', 'approver_role'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'adjustment_reason', 'warehouse', 'minimum_variance_qty', 'approver_role'), name='inv_adjust_rule_uq')],
            },
        ),
    ]
