from __future__ import annotations

from typing import Any

from .request import Request


class APIClient:
    def credentials(self, **kwargs: Any) -> None: ...

    def force_authenticate(self, user: Any = ..., token: Any = ...) -> None: ...

    def get(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Any: ...

    def post(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Any: ...

    def patch(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Any: ...

    def put(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Any: ...

    def delete(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Any: ...


class APIRequestFactory:
    def get(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Request: ...

    def post(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Request: ...

    def patch(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Request: ...

    def put(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Request: ...

    def delete(self, path: str, data: Any = ..., format: str | None = ..., **extra: Any) -> Request: ...


class APITestCase:
    client: APIClient


def force_authenticate(request: Request, user: Any = ..., token: Any = ...) -> None: ...
