# Generated by Django 5.2.12 on 2026-03-24 22:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_organizationaccessauditevent_action_type'),
        ('partners', '0002_customeraccount_operational_fields'),
        ('products', '0002_alter_productpackaging_height_cm_and_more'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('STANDARD', 'Standard'), ('B2B', 'B2B'), ('DROPSHIP', 'Dropshipping')], default='DROPSHIP', max_length=32)),
                ('order_number', models.CharField(max_length=64)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('requested_ship_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ALLOCATED', 'Allocated'), ('PICKING', 'Picking'), ('PICKED', 'Picked'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('fulfillment_stage', models.CharField(choices=[('GET_TRACKING_NO', 'Get Tracking No'), ('TO_MOVE', 'To Move'), ('IN_PROCESS', 'In Process Orders'), ('TO_SHIP', 'To Ship'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='GET_TRACKING_NO', max_length=32)),
                ('exception_state', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL_PACKAGE', 'Abnormal Package'), ('ORDER_INTERCEPTION', 'Order Interception')], default='NORMAL', max_length=32)),
                ('customer_code', models.CharField(blank=True, default='', max_length=64)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_contact_phone', models.CharField(blank=True, default='', max_length=64)),
                ('package_count', models.PositiveIntegerField(default=0)),
                ('package_type', models.CharField(blank=True, default='', max_length=64)),
                ('package_weight', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('package_length', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('package_width', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('package_height', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('package_volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('logistics_provider', models.CharField(blank=True, default='', max_length=64)),
                ('shipping_method', models.CharField(blank=True, default='', max_length=64)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=64)),
                ('waybill_number', models.CharField(blank=True, default='', max_length=64)),
                ('waybill_printed', models.BooleanField(default=False)),
                ('waybill_printed_at', models.DateTimeField(blank=True, null=True)),
                ('deliverer_name', models.CharField(blank=True, default='', max_length=255)),
                ('deliverer_phone', models.CharField(blank=True, default='', max_length=64)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=255)),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=64)),
                ('receiver_country', models.CharField(blank=True, default='', max_length=64)),
                ('receiver_state', models.CharField(blank=True, default='', max_length=64)),
                ('receiver_city', models.CharField(blank=True, default='', max_length=64)),
                ('receiver_address', models.CharField(blank=True, default='', max_length=255)),
                ('receiver_postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('picking_started_at', models.DateTimeField(blank=True, null=True)),
                ('picking_completed_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('exception_notes', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='partners.customeraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='organizations.organization')),
                ('staging_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='locations.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-create_time', '-id'),
                'permissions': [('view_outbound', 'Can view outbound operations'), ('manage_outbound_orders', 'Can manage outbound orders'), ('manage_outbound_execution', 'Can manage outbound execution')],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('ordered_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('picked_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('shipped_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ALLOCATED', 'Allocated'), ('PARTIAL', 'Partial'), ('PICKED', 'Picked'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_lines', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_lines', to='products.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='outbound.salesorder')),
            ],
            options={
                'ordering': ('organization_id', 'sales_order_id', 'line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PickTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('completed_by', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pick_tasks', to='organizations.organizationmembership')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks_from', to='locations.location')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_tasks', to='inventory.inventorymovement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='organizations.organization')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks_to', to='locations.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='warehouse.warehouse')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_tasks', to='outbound.salesorderline')),
            ],
            options={
                'ordering': ('organization_id', 'sales_order_line_id', 'task_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=32)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=64)),
                ('shipped_by', models.CharField(max_length=255)),
                ('shipped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='organizations.organization')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='outbound.salesorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-shipped_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_lines', to='inventory.inventorymovement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_lines', to='organizations.organization')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_lines', to='outbound.salesorderline')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='outbound.shipment')),
            ],
            options={
                'ordering': ('organization_id', 'shipment_id', 'sales_order_line_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('organization', 'order_number'), name='unique_sales_order_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('sales_order', 'line_number'), name='unique_sales_order_line_number_per_order'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gte', models.F('allocated_qty'))), name='sales_order_line_allocated_lte_ordered'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gte', models.F('picked_qty'))), name='sales_order_line_picked_lte_ordered'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_qty__gte', models.F('shipped_qty'))), name='sales_order_line_shipped_lte_ordered'),
        ),
        migrations.AddConstraint(
            model_name='picktask',
            constraint=models.UniqueConstraint(fields=('organization', 'task_number'), name='unique_pick_task_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.UniqueConstraint(fields=('organization', 'shipment_number'), name='unique_shipment_number_per_organization'),
        ),
    ]
