# Generated by Django 5.2.12 on 2026-03-14 02:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_creater_creator'),
        ('locations', '0001_initial'),
        ('scanner', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsScanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('requires_lot', models.BooleanField(default=False, verbose_name='Requires Lot')),
                ('requires_serial', models.BooleanField(default=False, verbose_name='Requires Serial')),
                ('lot_pattern', models.CharField(blank=True, default='', max_length=255, verbose_name='Lot Pattern')),
                ('serial_pattern', models.CharField(blank=True, default='', max_length=255, verbose_name='Serial Pattern')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scan_rule', to='goods.listmodel', verbose_name='Goods')),
            ],
            options={
                'verbose_name': 'Goods Scan Rule',
                'verbose_name_plural': 'Goods Scan Rules',
                'db_table': 'scanner_goods_scan_rule',
                'ordering': ['goods_id'],
            },
        ),
        migrations.CreateModel(
            name='BarcodeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('target_type', models.CharField(choices=[('GOODS', 'Goods'), ('LOCATION', 'Location')], max_length=32, verbose_name='Target Type')),
                ('alias_code', models.CharField(max_length=255, verbose_name='Alias Code')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barcode_aliases', to='goods.listmodel', verbose_name='Goods')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barcode_aliases', to='locations.location', verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Barcode Alias',
                'verbose_name_plural': 'Barcode Aliases',
                'db_table': 'scanner_barcode_alias',
                'ordering': ['target_type', 'alias_code', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'target_type', 'alias_code'), name='scanner_barcode_alias_unique')],
            },
        ),
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('lpn_code', models.CharField(max_length=128, verbose_name='LPN Code')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('RECEIVED', 'Received'), ('STORED', 'Stored'), ('STAGED', 'Staged'), ('LOADED', 'Loaded')], default='EXPECTED', max_length=16, verbose_name='Status')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='license_plates', to='locations.location', verbose_name='Current Location')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_plates', to='goods.listmodel', verbose_name='Goods')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_plates', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'License Plate',
                'verbose_name_plural': 'License Plates',
                'db_table': 'scanner_license_plate',
                'ordering': ['-update_time', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'lpn_code'), name='scanner_license_plate_unique')],
            },
        ),
    ]
