# Generated by Django 5.2.12 on 2026-03-14 11:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_goodsscanrule_barcodealias_licenseplate'),
        ('staff', '0002_rename_creater_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandheldDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('device_id', models.CharField(max_length=128, verbose_name='Device ID')),
                ('device_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Device Label')),
                ('app_version', models.CharField(blank=True, default='', max_length=64, verbose_name='App Version')),
                ('platform', models.CharField(blank=True, default='', max_length=64, verbose_name='Platform')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=16, verbose_name='Status')),
                ('session_started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Session Started At')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Seen At')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync At')),
                ('session_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Session Ended At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handheld_sessions', to='staff.listmodel', verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Handheld Device Session',
                'verbose_name_plural': 'Handheld Device Sessions',
                'db_table': 'scanner_handheld_device_session',
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OfflineReplayBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('client_batch_id', models.CharField(max_length=128, verbose_name='Client Batch ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=16, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('event_count', models.PositiveIntegerField(default=0, verbose_name='Event Count')),
                ('replayed_count', models.PositiveIntegerField(default=0, verbose_name='Replayed Count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Failed Count')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_replay_batches', to='staff.listmodel', verbose_name='Operator')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replay_batches', to='scanner.handhelddevicesession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Offline Replay Batch',
                'verbose_name_plural': 'Offline Replay Batches',
                'db_table': 'scanner_offline_replay_batch',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OfflineReplayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='Sequence Number')),
                ('event_type', models.CharField(choices=[('INBOUND_RECEIVE', 'Inbound Receive'), ('INBOUND_PUTAWAY', 'Inbound Putaway'), ('OUTBOUND_PICK', 'Outbound Pick'), ('OUTBOUND_SHIP', 'Outbound Ship')], max_length=32, verbose_name='Event Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], default='PENDING', max_length=16, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('result_record_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Result Record Type')),
                ('result_record_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Result Record ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='scanner.offlinereplaybatch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Offline Replay Event',
                'verbose_name_plural': 'Offline Replay Events',
                'db_table': 'scanner_offline_replay_event',
                'ordering': ['batch_id', 'sequence_number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='handhelddevicesession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False), ('status', 'ACTIVE')), fields=('openid', 'device_id'), name='scanner_handheld_device_session_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='offlinereplaybatch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'session', 'client_batch_id'), name='scanner_offline_replay_batch_unique'),
        ),
        migrations.AddConstraint(
            model_name='offlinereplayevent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'batch', 'sequence_number'), name='scanner_offline_replay_event_unique'),
        ),
    ]
