# Generated by Django 5.2.12 on 2026-03-14 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_handhelddevicesession_offlinereplaybatch_and_more'),
        ('staff', '0002_rename_creater_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='handhelddevicesession',
            name='last_battery_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Last Battery Level'),
        ),
        migrations.AddField(
            model_name='handhelddevicesession',
            name='last_network_type',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Last Network Type'),
        ),
        migrations.AddField(
            model_name='handhelddevicesession',
            name='last_signal_strength',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last Signal Strength'),
        ),
        migrations.AddField(
            model_name='handhelddevicesession',
            name='telemetry_sample_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Telemetry Sample Count'),
        ),
        migrations.AddField(
            model_name='handhelddevicesession',
            name='total_conflict_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Conflict Count'),
        ),
        migrations.AddField(
            model_name='handhelddevicesession',
            name='total_failure_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Failure Count'),
        ),
        migrations.AddField(
            model_name='handhelddevicesession',
            name='total_replayed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Replayed Count'),
        ),
        migrations.AddField(
            model_name='handhelddevicesession',
            name='total_scan_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Scan Count'),
        ),
        migrations.AddField(
            model_name='handhelddevicesession',
            name='total_sync_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Sync Count'),
        ),
        migrations.AddField(
            model_name='offlinereplaybatch',
            name='conflict_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Conflict Count'),
        ),
        migrations.AddField(
            model_name='offlinereplayevent',
            name='conflict_key',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Conflict Key'),
        ),
        migrations.AddField(
            model_name='offlinereplayevent',
            name='conflict_rule',
            field=models.CharField(blank=True, choices=[('IDEMPOTENT_SKIP', 'Idempotent Skip'), ('MANUAL_REVIEW', 'Manual Review'), ('REJECT', 'Reject')], default='', max_length=32, verbose_name='Conflict Rule'),
        ),
        migrations.AddField(
            model_name='offlinereplayevent',
            name='conflict_type',
            field=models.CharField(blank=True, choices=[('DUPLICATE_REFERENCE', 'Duplicate Reference'), ('STATE_MISMATCH', 'State Mismatch'), ('TASK_ALREADY_COMPLETED', 'Task Already Completed'), ('ORDER_ALREADY_SHIPPED', 'Order Already Shipped'), ('STALE_REFERENCE', 'Stale Reference')], default='', max_length=32, verbose_name='Conflict Type'),
        ),
        migrations.AddField(
            model_name='offlinereplayevent',
            name='result_summary',
            field=models.TextField(blank=True, default='', verbose_name='Result Summary'),
        ),
        migrations.AlterField(
            model_name='offlinereplaybatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CONFLICTED', 'Conflicted'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='offlinereplayevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('SKIPPED', 'Skipped'), ('CONFLICT', 'Conflict'), ('FAILED', 'Failed')], default='PENDING', max_length=16, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='HandheldTelemetrySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recorded At')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='Scan Count')),
                ('queued_event_count', models.PositiveIntegerField(default=0, verbose_name='Queued Event Count')),
                ('sync_count', models.PositiveIntegerField(default=0, verbose_name='Sync Count')),
                ('replay_conflict_count', models.PositiveIntegerField(default=0, verbose_name='Replay Conflict Count')),
                ('replay_failure_count', models.PositiveIntegerField(default=0, verbose_name='Replay Failure Count')),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Battery Level')),
                ('network_type', models.CharField(blank=True, default='', max_length=32, verbose_name='Network Type')),
                ('signal_strength', models.IntegerField(blank=True, null=True, verbose_name='Signal Strength')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Latency Ms')),
                ('storage_free_mb', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Storage Free Mb')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handheld_telemetry_samples', to='staff.listmodel', verbose_name='Operator')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telemetry_samples', to='scanner.handhelddevicesession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Handheld Telemetry Sample',
                'verbose_name_plural': 'Handheld Telemetry Samples',
                'db_table': 'scanner_handheld_telemetry_sample',
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
