# Generated by Django 5.2.12 on 2026-03-20 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('membership_type', models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('CLIENT', 'Client')], max_length=20, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_groups', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AccessGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='iam.accessgroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='AccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('WAREHOUSE', 'Warehouse'), ('RESOURCE', 'Resource')], max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_key', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to='organizations.organization')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='iam.accessgroup')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='organizations.organizationmembership')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='iam.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='organizations.organizationmembership')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='auth.permission')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='iam.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('membership_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('CLIENT', 'Client')], default='INTERNAL', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='organizations.organizationmembership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='iam.role')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='iam.accessscope')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='auth.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='iam.role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accessgroup',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_group_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='accessgrouppermission',
            constraint=models.UniqueConstraint(fields=('group', 'permission'), name='unique_permission_per_group'),
        ),
        migrations.AddConstraint(
            model_name='accessscope',
            constraint=models.UniqueConstraint(fields=('organization', 'scope_type', 'warehouse', 'resource_type', 'resource_key'), name='unique_access_scope_target'),
        ),
        migrations.AddConstraint(
            model_name='groupassignment',
            constraint=models.UniqueConstraint(fields=('membership', 'group', 'scope'), name='unique_group_assignment_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='permissionoverride',
            constraint=models.UniqueConstraint(fields=('membership', 'permission', 'scope'), name='unique_permission_override_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_role_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('membership', 'role', 'scope'), name='unique_role_assignment_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_permission_per_role'),
        ),
    ]
