# Generated by Django 5.2.12 on 2026-03-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': [('manage_memberships', 'Can manage organization memberships'), ('manage_client_users', 'Can manage client users')]},
        ),
    ]
