# Generated by Django 5.2.12 on 2026-03-22 13:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_options_and_more'),
        ('partners', '0002_customeraccount_operational_fields'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('workstream', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('INVENTORY', 'Inventory'), ('RETURNS', 'Returns'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('default_urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('default_priority_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('target_sla_hours', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)])),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_types', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'workstream', 'name', 'id'),
                'permissions': [('manage_work_order_types', 'Can manage work order types')],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('READY', 'Ready'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_REVIEW', max_length=20)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('priority_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('assignee_name', models.CharField(blank=True, default='', max_length=255)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='partners.customeraccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='organizations.organization')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='warehouse.warehouse')),
                ('work_order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workorders.workordertype')),
            ],
            options={
                'ordering': ('organization_id', '-priority_score', 'due_at', 'id'),
                'permissions': [('manage_work_orders', 'Can manage work orders')],
            },
        ),
        migrations.AddConstraint(
            model_name='workordertype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_work_order_type_code_per_organization'),
        ),
    ]
