from django.urls import path

from .views import (
    OrganizationBalanceTransactionDetailAPIView,
    OrganizationBalanceTransactionListCreateAPIView,
    OrganizationBusinessExpenseDetailAPIView,
    OrganizationBusinessExpenseListCreateAPIView,
    OrganizationChargeItemDetailAPIView,
    OrganizationChargeItemListCreateAPIView,
    OrganizationChargeTemplateDetailAPIView,
    OrganizationChargeTemplateListCreateAPIView,
    OrganizationFundFlowDetailAPIView,
    OrganizationFundFlowListCreateAPIView,
    OrganizationManualChargeDetailAPIView,
    OrganizationManualChargeListCreateAPIView,
    OrganizationProfitCalculationDetailAPIView,
    OrganizationProfitCalculationListCreateAPIView,
    OrganizationReceivableBillDetailAPIView,
    OrganizationReceivableBillListCreateAPIView,
    OrganizationRentDetailDetailAPIView,
    OrganizationRentDetailListCreateAPIView,
    OrganizationVoucherDetailAPIView,
    OrganizationVoucherListCreateAPIView,
)

urlpatterns = [
    path(
        "organizations/<int:organization_id>/fees/balance-transactions/",
        OrganizationBalanceTransactionListCreateAPIView.as_view(),
        name="organization-balance-transaction-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/balance-transactions/<int:balance_transaction_id>/",
        OrganizationBalanceTransactionDetailAPIView.as_view(),
        name="organization-balance-transaction-detail",
    ),
    path(
        "organizations/<int:organization_id>/fees/vouchers/",
        OrganizationVoucherListCreateAPIView.as_view(),
        name="organization-voucher-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/vouchers/<int:voucher_id>/",
        OrganizationVoucherDetailAPIView.as_view(),
        name="organization-voucher-detail",
    ),
    path(
        "organizations/<int:organization_id>/fees/charge-items/",
        OrganizationChargeItemListCreateAPIView.as_view(),
        name="organization-charge-item-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/charge-items/<int:charge_item_id>/",
        OrganizationChargeItemDetailAPIView.as_view(),
        name="organization-charge-item-detail",
    ),
    path(
        "organizations/<int:organization_id>/fees/charge-templates/",
        OrganizationChargeTemplateListCreateAPIView.as_view(),
        name="organization-charge-template-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/charge-templates/<int:charge_template_id>/",
        OrganizationChargeTemplateDetailAPIView.as_view(),
        name="organization-charge-template-detail",
    ),
    path(
        "organizations/<int:organization_id>/fees/manual-charges/",
        OrganizationManualChargeListCreateAPIView.as_view(),
        name="organization-manual-charge-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/manual-charges/<int:manual_charge_id>/",
        OrganizationManualChargeDetailAPIView.as_view(),
        name="organization-manual-charge-detail",
    ),
    path(
        "organizations/<int:organization_id>/fees/fund-flows/",
        OrganizationFundFlowListCreateAPIView.as_view(),
        name="organization-fund-flow-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/fund-flows/<int:fund_flow_id>/",
        OrganizationFundFlowDetailAPIView.as_view(),
        name="organization-fund-flow-detail",
    ),
    path(
        "organizations/<int:organization_id>/fees/rent-details/",
        OrganizationRentDetailListCreateAPIView.as_view(),
        name="organization-rent-detail-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/rent-details/<int:rent_detail_id>/",
        OrganizationRentDetailDetailAPIView.as_view(),
        name="organization-rent-detail-detail",
    ),
    path(
        "organizations/<int:organization_id>/fees/business-expenses/",
        OrganizationBusinessExpenseListCreateAPIView.as_view(),
        name="organization-business-expense-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/business-expenses/<int:business_expense_id>/",
        OrganizationBusinessExpenseDetailAPIView.as_view(),
        name="organization-business-expense-detail",
    ),
    path(
        "organizations/<int:organization_id>/fees/receivable-bills/",
        OrganizationReceivableBillListCreateAPIView.as_view(),
        name="organization-receivable-bill-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/receivable-bills/<int:receivable_bill_id>/",
        OrganizationReceivableBillDetailAPIView.as_view(),
        name="organization-receivable-bill-detail",
    ),
    path(
        "organizations/<int:organization_id>/fees/profit-calculations/",
        OrganizationProfitCalculationListCreateAPIView.as_view(),
        name="organization-profit-calculation-list",
    ),
    path(
        "organizations/<int:organization_id>/fees/profit-calculations/<int:profit_calculation_id>/",
        OrganizationProfitCalculationDetailAPIView.as_view(),
        name="organization-profit-calculation-detail",
    ),
]

