from django.urls import path

from apps.counting.api.views import (
    CountApprovalApproveAPIView,
    CountApprovalListAPIView,
    CountApprovalRejectAPIView,
    CycleCountDetailAPIView,
    CycleCountLineAssignAPIView,
    CycleCountLineAssignRecountAPIView,
    CycleCountLineDetailAPIView,
    CycleCountLineListAPIView,
    CycleCountLineMyAssignmentsAPIView,
    CycleCountLineNextTaskAPIView,
    CycleCountLineRecountAPIView,
    CycleCountLineScanCountAPIView,
    CycleCountLineScanLookupAPIView,
    CycleCountLineScannerAckAPIView,
    CycleCountLineScannerCompleteAPIView,
    CycleCountLineScannerStartAPIView,
    CycleCountListCreateAPIView,
    CycleCountSubmitAPIView,
)


urlpatterns = [
    path(
        "organizations/<int:organization_id>/counting/cycle-counts/",
        CycleCountListCreateAPIView.as_view(),
        name="organization-cycle-count-list",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-counts/<int:cycle_count_id>/",
        CycleCountDetailAPIView.as_view(),
        name="organization-cycle-count-detail",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-counts/<int:cycle_count_id>/submit/",
        CycleCountSubmitAPIView.as_view(),
        name="organization-cycle-count-submit",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/",
        CycleCountLineListAPIView.as_view(),
        name="organization-cycle-count-line-list",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/my-assignments/",
        CycleCountLineMyAssignmentsAPIView.as_view(),
        name="organization-cycle-count-line-my-assignments",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/next-task/",
        CycleCountLineNextTaskAPIView.as_view(),
        name="organization-cycle-count-line-next-task",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/scan-lookup/",
        CycleCountLineScanLookupAPIView.as_view(),
        name="organization-cycle-count-line-scan-lookup",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/scan-count/",
        CycleCountLineScanCountAPIView.as_view(),
        name="organization-cycle-count-line-scan-count",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/<int:cycle_count_line_id>/",
        CycleCountLineDetailAPIView.as_view(),
        name="organization-cycle-count-line-detail",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/<int:cycle_count_line_id>/assign/",
        CycleCountLineAssignAPIView.as_view(),
        name="organization-cycle-count-line-assign",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/<int:cycle_count_line_id>/assign-recount/",
        CycleCountLineAssignRecountAPIView.as_view(),
        name="organization-cycle-count-line-assign-recount",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/<int:cycle_count_line_id>/recount/",
        CycleCountLineRecountAPIView.as_view(),
        name="organization-cycle-count-line-recount",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/<int:cycle_count_line_id>/scanner-ack/",
        CycleCountLineScannerAckAPIView.as_view(),
        name="organization-cycle-count-line-scanner-ack",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/<int:cycle_count_line_id>/scanner-start/",
        CycleCountLineScannerStartAPIView.as_view(),
        name="organization-cycle-count-line-scanner-start",
    ),
    path(
        "organizations/<int:organization_id>/counting/cycle-count-lines/<int:cycle_count_line_id>/scanner-complete/",
        CycleCountLineScannerCompleteAPIView.as_view(),
        name="organization-cycle-count-line-scanner-complete",
    ),
    path(
        "organizations/<int:organization_id>/counting/approvals/",
        CountApprovalListAPIView.as_view(),
        name="organization-count-approval-list",
    ),
    path(
        "organizations/<int:organization_id>/counting/approvals/<int:approval_id>/approve/",
        CountApprovalApproveAPIView.as_view(),
        name="organization-count-approval-approve",
    ),
    path(
        "organizations/<int:organization_id>/counting/approvals/<int:approval_id>/reject/",
        CountApprovalRejectAPIView.as_view(),
        name="organization-count-approval-reject",
    ),
]
