# Generated by Django 5.2.12 on 2026-03-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'name', 'id'),
                'permissions': [('manage_customer_accounts', 'Can manage customer accounts'), ('manage_client_account_access', 'Can manage client account access'), ('view_inventory', 'Can view customer inventory'), ('view_orders', 'Can view customer orders'), ('view_charges', 'Can view customer charges'), ('submit_inbound_goods', 'Can submit inbound goods for customer account')],
            },
        ),
        migrations.CreateModel(
            name='ClientAccountAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_account_accesses', to='organizations.organizationmembership')),
                ('customer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accesses', to='partners.customeraccount')),
            ],
            options={
                'ordering': ('customer_account_id', 'membership_id', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='customeraccount',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_customer_account_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='clientaccountaccess',
            constraint=models.UniqueConstraint(fields=('membership', 'customer_account'), name='unique_membership_customer_account_access'),
        ),
    ]
