# Generated by Django 5.2.12 on 2026-03-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraccount",
            name="allow_dropshipping_orders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="allow_inbound_goods",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="customeraccount",
            name="shipping_method",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterModelOptions(
            name="customeraccount",
            options={
                "ordering": ("organization_id", "name", "id"),
                "permissions": [
                    ("manage_customer_accounts", "Can manage customer accounts"),
                    ("manage_client_account_access", "Can manage client account access"),
                    ("view_inventory", "Can view customer inventory"),
                    ("view_orders", "Can view customer orders"),
                    ("view_charges", "Can view customer charges"),
                    ("submit_dropshipping_orders", "Can submit dropshipping orders for customer account"),
                    ("submit_inbound_goods", "Can submit inbound goods for customer account"),
                ],
            },
        ),
    ]
