# Generated by Django 5.2.12 on 2026-03-13 22:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_rename_creater_creator'),
        ('goods', '0002_rename_creater_creator'),
        ('inventory', '0002_inventoryadjustmentreason_and_more'),
        ('locations', '0001_initial'),
        ('outbound', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('return_number', models.CharField(max_length=64, verbose_name='Return Number')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='Requested Date')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL_RECEIVED', 'Partial Received'), ('RECEIVED', 'Received'), ('PARTIAL_DISPOSED', 'Partial Disposed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to='customer.listmodel', verbose_name='Customer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to='outbound.salesorder', verbose_name='Sales Order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_orders', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Return Order',
                'verbose_name_plural': 'Return Orders',
                'db_table': 'returns_return_order',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('line_number', models.PositiveIntegerField(verbose_name='Line Number')),
                ('expected_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Expected Qty')),
                ('received_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Received Qty')),
                ('disposed_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Disposed Qty')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL_RECEIVED', 'Partial Received'), ('RECEIVED', 'Received'), ('PARTIAL_DISPOSED', 'Partial Disposed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('return_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Return Reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='goods.listmodel', verbose_name='Goods')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='returns.returnorder', verbose_name='Return Order')),
            ],
            options={
                'verbose_name': 'Return Line',
                'verbose_name_plural': 'Return Lines',
                'db_table': 'returns_return_line',
                'ordering': ['return_order_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='ReturnReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('receipt_number', models.CharField(max_length=64, verbose_name='Receipt Number')),
                ('received_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Received Qty')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='QUARANTINE', max_length=32, verbose_name='Stock Status')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('received_by', models.CharField(max_length=255, verbose_name='Received By')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Received At')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_receipts', to='inventory.inventorymovement', verbose_name='Inventory Movement')),
                ('receipt_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_receipts', to='locations.location', verbose_name='Receipt Location')),
                ('return_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='returns.returnline', verbose_name='Return Line')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_receipts', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Return Receipt',
                'verbose_name_plural': 'Return Receipts',
                'db_table': 'returns_return_receipt',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('disposition_number', models.CharField(max_length=64, verbose_name='Disposition Number')),
                ('disposition_type', models.CharField(choices=[('RESTOCK', 'Restock'), ('QUARANTINE', 'Quarantine'), ('SCRAP', 'Scrap')], max_length=32, verbose_name='Disposition Type')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('completed_by', models.CharField(max_length=255, verbose_name='Completed By')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Completed At')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_dispositions', to='inventory.inventorymovement', verbose_name='Inventory Movement')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_dispositions', to='locations.location', verbose_name='To Location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_dispositions', to='warehouse.warehouse', verbose_name='Warehouse')),
                ('return_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositions', to='returns.returnreceipt', verbose_name='Return Receipt')),
            ],
            options={
                'verbose_name': 'Return Disposition',
                'verbose_name_plural': 'Return Dispositions',
                'db_table': 'returns_return_disposition',
                'ordering': ['-completed_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='returnorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'return_number'), name='returns_return_order_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('return_order', 'line_number'), name='returns_return_line_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_qty__gte', models.F('received_qty'))), name='returns_expected_gte_received'),
        ),
        migrations.AddConstraint(
            model_name='returnline',
            constraint=models.CheckConstraint(condition=models.Q(('received_qty__gte', models.F('disposed_qty'))), name='returns_received_gte_disposed'),
        ),
        migrations.AddConstraint(
            model_name='returnreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'receipt_number'), name='returns_receipt_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='returndisposition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'disposition_number'), name='returns_disposition_number_uq'),
        ),
    ]
