# Generated by Django 5.2.12 on 2026-03-24 02:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_alter_organizationaccessauditevent_action_type'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('picking_enabled', models.BooleanField(default=True)),
                ('putaway_enabled', models.BooleanField(default=True)),
                ('allow_mixed_sku', models.BooleanField(default=False)),
                ('max_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_types', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', 'code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('usage', models.CharField(choices=[('RECEIVING', 'Receiving'), ('STORAGE', 'Storage'), ('PICKING', 'Picking'), ('SHIPPING', 'Shipping'), ('QUARANTINE', 'Quarantine'), ('RETURNS', 'Returns')], default='STORAGE', max_length=32)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='organizations.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', 'warehouse_id', 'sequence', 'code', 'id'),
                'permissions': [('manage_location_topology', 'Can manage location topology')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('aisle', models.CharField(blank=True, default='', max_length=64)),
                ('bay', models.CharField(blank=True, default='', max_length=64)),
                ('level', models.CharField(blank=True, default='', max_length=64)),
                ('slot', models.CharField(blank=True, default='', max_length=64)),
                ('barcode', models.CharField(blank=True, default='', max_length=255)),
                ('capacity_qty', models.PositiveIntegerField(default=0)),
                ('max_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('pick_sequence', models.PositiveIntegerField(default=0)),
                ('is_pick_face', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouse.warehouse')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.locationtype')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='locations.zone')),
            ],
            options={
                'ordering': ('organization_id', 'warehouse_id', 'pick_sequence', 'code', 'id'),
                'permissions': [('view_locations', 'Can view location topology')],
            },
        ),
        migrations.CreateModel(
            name='LocationLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('locked_by', models.CharField(max_length=255)),
                ('released_by', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='locations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_locks', to='organizations.organization')),
            ],
            options={
                'ordering': ('organization_id', '-start_time', '-id'),
                'permissions': [('manage_location_locks', 'Can manage location locks')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('location',), name='unique_active_location_lock_per_location')],
            },
        ),
        migrations.AddConstraint(
            model_name='locationtype',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_location_type_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_zone_code_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('warehouse', 'name'), name='unique_zone_name_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_location_code_per_warehouse'),
        ),
    ]
