# Generated by Django 5.2.12 on 2026-03-14 00:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_rename_creater_creator'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('report_type', models.CharField(choices=[('INVENTORY_AGING', 'Inventory Aging'), ('RECEIVING_THROUGHPUT', 'Receiving Throughput'), ('SHIPPING_THROUGHPUT', 'Shipping Throughput')], max_length=32, verbose_name='Report Type')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('EXPIRED', 'Expired')], default='GENERATED', max_length=16, verbose_name='Status')),
                ('export_format', models.CharField(default='csv', max_length=16, verbose_name='Export Format')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Date From')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Date To')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Row Count')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generated At')),
                ('generated_by', models.CharField(max_length=255, verbose_name='Generated By')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Operational Report Export',
                'verbose_name_plural': 'Operational Report Exports',
                'db_table': 'reporting_operational_report_export',
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BillingChargeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('charge_type', models.CharField(choices=[('STORAGE_DAILY', 'Storage Daily'), ('RECEIPT_HANDLING', 'Receipt Handling'), ('SHIPMENT_HANDLING', 'Shipment Handling'), ('RETURN_HANDLING', 'Return Handling'), ('LABEL_GENERATION', 'Label Generation'), ('EXTRA_SCAN', 'Extra Scan')], max_length=32, verbose_name='Charge Type')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Quantity')),
                ('uom', models.CharField(default='EA', max_length=16, verbose_name='UOM')),
                ('unit_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Unit Rate')),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Currency')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVOICED', 'Invoiced'), ('VOID', 'Void')], default='OPEN', max_length=16, verbose_name='Status')),
                ('source_module', models.CharField(blank=True, default='', max_length=64, verbose_name='Source Module')),
                ('source_record_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Source Record Type')),
                ('source_record_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Source Record ID')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_charge_events', to='customer.listmodel', verbose_name='Customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_charge_events', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Billing Charge Event',
                'verbose_name_plural': 'Billing Charge Events',
                'db_table': 'reporting_billing_charge_event',
                'ordering': ['-event_date', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False), ('source_record_id__isnull', False)), fields=('openid', 'charge_type', 'source_module', 'source_record_type', 'source_record_id'), name='reporting_charge_event_source_unique')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('snapshot_date', models.DateField(verbose_name='Snapshot Date')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generated At')),
                ('generated_by', models.CharField(max_length=255, verbose_name='Generated By')),
                ('on_hand_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='On Hand Qty')),
                ('available_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Available Qty')),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Allocated Qty')),
                ('hold_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Hold Qty')),
                ('open_purchase_orders', models.PositiveIntegerField(default=0, verbose_name='Open Purchase Orders')),
                ('open_sales_orders', models.PositiveIntegerField(default=0, verbose_name='Open Sales Orders')),
                ('open_putaway_tasks', models.PositiveIntegerField(default=0, verbose_name='Open Putaway Tasks')),
                ('open_pick_tasks', models.PositiveIntegerField(default=0, verbose_name='Open Pick Tasks')),
                ('pending_count_approvals', models.PositiveIntegerField(default=0, verbose_name='Pending Count Approvals')),
                ('pending_return_orders', models.PositiveIntegerField(default=0, verbose_name='Pending Return Orders')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_snapshots', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse KPI Snapshot',
                'verbose_name_plural': 'Warehouse KPI Snapshots',
                'db_table': 'reporting_warehouse_kpi_snapshot',
                'ordering': ['-snapshot_date', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'warehouse', 'snapshot_date'), name='reporting_kpi_snapshot_unique')],
            },
        ),
    ]
