# Generated by Django 5.2.12 on 2026-03-14 01:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_creater_creator'),
        ('reporting', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingchargeevent',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rated At'),
        ),
        migrations.AddField(
            model_name='billingchargeevent',
            name='rated_by',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Rated By'),
        ),
        migrations.CreateModel(
            name='BillingRateContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('contract_name', models.CharField(max_length=128, verbose_name='Contract Name')),
                ('charge_type', models.CharField(choices=[('STORAGE_DAILY', 'Storage Daily'), ('RECEIPT_HANDLING', 'Receipt Handling'), ('SHIPMENT_HANDLING', 'Shipment Handling'), ('RETURN_HANDLING', 'Return Handling'), ('LABEL_GENERATION', 'Label Generation'), ('EXTRA_SCAN', 'Extra Scan')], max_length=32, verbose_name='Charge Type')),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Unit Rate')),
                ('minimum_charge', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Minimum Charge')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Currency')),
                ('uom', models.CharField(default='EA', max_length=16, verbose_name='UOM')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='Effective To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_rate_contracts', to='customer.listmodel', verbose_name='Customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_rate_contracts', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Billing Rate Contract',
                'verbose_name_plural': 'Billing Rate Contracts',
                'db_table': 'reporting_billing_rate_contract',
                'ordering': ['priority', '-effective_from', 'id'],
            },
        ),
        migrations.AddField(
            model_name='billingchargeevent',
            name='rate_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_events', to='reporting.billingratecontract', verbose_name='Rate Contract'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('invoice_number', models.CharField(max_length=64, verbose_name='Invoice Number')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('VOID', 'Void')], default='DRAFT', max_length=16, verbose_name='Status')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Currency')),
                ('subtotal_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Subtotal Amount')),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Tax Amount')),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Total Amount')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generated At')),
                ('generated_by', models.CharField(max_length=255, verbose_name='Generated By')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalized At')),
                ('finalized_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Finalized By')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customer.listmodel', verbose_name='Customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'reporting_invoice',
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('charge_type', models.CharField(choices=[('STORAGE_DAILY', 'Storage Daily'), ('RECEIPT_HANDLING', 'Receipt Handling'), ('SHIPMENT_HANDLING', 'Shipment Handling'), ('RETURN_HANDLING', 'Return Handling'), ('LABEL_GENERATION', 'Label Generation'), ('EXTRA_SCAN', 'Extra Scan')], max_length=32, verbose_name='Charge Type')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Quantity')),
                ('uom', models.CharField(default='EA', max_length=16, verbose_name='UOM')),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Unit Rate')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Amount')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('charge_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line', to='reporting.billingchargeevent', verbose_name='Billing Charge Event')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='reporting.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'db_table': 'reporting_invoice_line',
                'ordering': ['invoice_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingratecontract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'warehouse', 'customer', 'charge_type', 'contract_name', 'effective_from'), name='reporting_rate_contract_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'invoice_number'), name='reporting_invoice_number_unique'),
        ),
    ]
