# Generated by Django 5.2.12 on 2026-03-14 02:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_creater_creator'),
        ('reporting', '0002_billingchargeevent_rated_at_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('EXPIRED', 'Expired')], default='GENERATED', max_length=16, verbose_name='Status')),
                ('export_format', models.CharField(default='csv', max_length=16, verbose_name='Export Format')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Row Count')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generated At')),
                ('generated_by', models.CharField(max_length=255, verbose_name='Generated By')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_exports', to='customer.listmodel', verbose_name='Customer')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_exports', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Finance Export',
                'verbose_name_plural': 'Finance Exports',
                'db_table': 'reporting_finance_export',
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceFinanceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('submitted_by', models.CharField(max_length=255, verbose_name='Submitted By')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Reviewed By')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance_approval', to='reporting.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Invoice Finance Approval',
                'verbose_name_plural': 'Invoice Finance Approvals',
                'db_table': 'reporting_invoice_finance_approval',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StorageAccrualRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('accrual_date', models.DateField(verbose_name='Accrual Date')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('VOID', 'Void')], default='GENERATED', max_length=16, verbose_name='Status')),
                ('basis', models.CharField(default='CURRENT_ON_HAND_SNAPSHOT', max_length=64, verbose_name='Basis')),
                ('balance_count', models.PositiveIntegerField(default=0, verbose_name='Balance Count')),
                ('total_on_hand_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Total On Hand Qty')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generated At')),
                ('generated_by', models.CharField(max_length=255, verbose_name='Generated By')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('charge_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_accrual_run', to='reporting.billingchargeevent', verbose_name='Charge Event')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_accrual_runs', to='customer.listmodel', verbose_name='Customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_accrual_runs', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Storage Accrual Run',
                'verbose_name_plural': 'Storage Accrual Runs',
                'db_table': 'reporting_storage_accrual_run',
                'ordering': ['-accrual_date', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'warehouse', 'customer', 'accrual_date'), name='reporting_storage_accrual_run_unique')],
            },
        ),
    ]
