# Generated by Django 5.2.12 on 2026-03-14 11:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_financeexport_invoicefinanceapproval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='OPEN', max_length=16, verbose_name='Status')),
                ('reason_code', models.CharField(choices=[('RATE', 'Rate'), ('QUANTITY', 'Quantity'), ('SERVICE', 'Service'), ('DAMAGE', 'Damage'), ('OTHER', 'Other')], max_length=16, verbose_name='Reason Code')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('disputed_amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Disputed Amount')),
                ('approved_credit_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Approved Credit Amount')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opened At')),
                ('opened_by', models.CharField(max_length=255, verbose_name='Opened By')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Reviewed By')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolved_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Resolved By')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('resolution_notes', models.TextField(blank=True, default='', verbose_name='Resolution Notes')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='reporting.invoice', verbose_name='Invoice')),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='reporting.invoiceline', verbose_name='Invoice Line')),
            ],
            options={
                'verbose_name': 'Invoice Dispute',
                'verbose_name_plural': 'Invoice Disputes',
                'db_table': 'reporting_invoice_dispute',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('PARTIALLY_REMITTED', 'Partially Remitted'), ('REMITTED', 'Remitted'), ('REJECTED', 'Rejected')], default='PENDING_APPROVAL', max_length=24, verbose_name='Status')),
                ('requested_amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Requested Amount')),
                ('approved_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Approved Amount')),
                ('remitted_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='Remitted Amount')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Currency')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('settlement_reference', models.CharField(blank=True, default='', max_length=64, verbose_name='Settlement Reference')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('submitted_by', models.CharField(max_length=255, verbose_name='Submitted By')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Reviewed By')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='reporting.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Invoice Settlement',
                'verbose_name_plural': 'Invoice Settlements',
                'db_table': 'reporting_invoice_settlement',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('VOID', 'Void')], default='POSTED', max_length=16, verbose_name='Status')),
                ('remittance_reference', models.CharField(max_length=64, verbose_name='Remittance Reference')),
                ('remitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Remitted At')),
                ('remitted_by', models.CharField(max_length=255, verbose_name='Remitted By')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Currency')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='reporting.invoicesettlement', verbose_name='Settlement')),
            ],
            options={
                'verbose_name': 'Invoice Remittance',
                'verbose_name_plural': 'Invoice Remittances',
                'db_table': 'reporting_invoice_remittance',
                'ordering': ['-remitted_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'remittance_reference'), name='reporting_invoice_remittance_reference_unique')],
            },
        ),
    ]
