# Generated by Django 5.2.12 on 2026-03-14 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_invoicedispute_invoicesettlement_invoiceremittance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceremittance',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='External Reference'),
        ),
        migrations.AddField(
            model_name='invoiceremittance',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('EXTERNAL', 'External')], default='MANUAL', max_length=16, verbose_name='Source'),
        ),
        migrations.CreateModel(
            name='ExternalRemittanceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('source_system', models.CharField(max_length=64, verbose_name='Source System')),
                ('external_batch_id', models.CharField(max_length=128, verbose_name='External Batch ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=16, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('item_count', models.PositiveIntegerField(default=0, verbose_name='Item Count')),
                ('applied_count', models.PositiveIntegerField(default=0, verbose_name='Applied Count')),
                ('conflict_count', models.PositiveIntegerField(default=0, verbose_name='Conflict Count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Failed Count')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last Error')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'External Remittance Batch',
                'verbose_name_plural': 'External Remittance Batches',
                'db_table': 'reporting_external_remittance_batch',
                'ordering': ['-submitted_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'source_system', 'external_batch_id'), name='reporting_external_remittance_batch_unique')],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('credit_note_number', models.CharField(max_length=64, verbose_name='Credit Note Number')),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('APPLIED', 'Applied'), ('VOID', 'Void')], default='ISSUED', max_length=16, verbose_name='Status')),
                ('reason_code', models.CharField(choices=[('RATE', 'Rate'), ('QUANTITY', 'Quantity'), ('SERVICE', 'Service'), ('DAMAGE', 'Damage'), ('OTHER', 'Other')], default='OTHER', max_length=16, verbose_name='Reason Code')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Currency')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued At')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Issued By')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Applied At')),
                ('applied_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Applied By')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('dispute', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note', to='reporting.invoicedispute', verbose_name='Dispute')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='reporting.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'db_table': 'reporting_credit_note',
                'ordering': ['-issued_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'credit_note_number'), name='reporting_credit_note_number_unique')],
            },
        ),
        migrations.CreateModel(
            name='ExternalRemittanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('external_reference', models.CharField(max_length=128, verbose_name='External Reference')),
                ('matched_invoice_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Matched Invoice Number')),
                ('matched_settlement_reference', models.CharField(blank=True, default='', max_length=64, verbose_name='Matched Settlement Reference')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=8, verbose_name='Currency')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SKIPPED', 'Skipped'), ('CONFLICT', 'Conflict'), ('FAILED', 'Failed')], default='APPLIED', max_length=16, verbose_name='Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='reporting.externalremittancebatch', verbose_name='Batch')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_remittance_items', to='reporting.invoice', verbose_name='Invoice')),
                ('remittance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_ingestion_item', to='reporting.invoiceremittance', verbose_name='Remittance')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_remittance_items', to='reporting.invoicesettlement', verbose_name='Settlement')),
            ],
            options={
                'verbose_name': 'External Remittance Item',
                'verbose_name_plural': 'External Remittance Items',
                'db_table': 'reporting_external_remittance_item',
                'ordering': ['batch_id', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'batch', 'external_reference'), name='reporting_external_remittance_item_unique')],
            },
        ),
    ]
