# Generated by Django 5.2.12 on 2026-03-15 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('openid', models.CharField(db_index=True, max_length=100, verbose_name='OpenID')),
                ('username', models.CharField(max_length=150, verbose_name='User Name')),
                ('operator_id', models.PositiveIntegerField(verbose_name='Operator ID')),
                ('operator_name', models.CharField(max_length=255, verbose_name='Operator Name')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='PENDING', max_length=32, verbose_name='Status')),
                ('verified_method', models.CharField(blank=True, choices=[('TOTP', 'Authenticator app'), ('RECOVERY_CODE', 'Recovery code')], default='', max_length=32, verbose_name='Verified Method')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Consumed At')),
                ('ip', models.CharField(blank=True, default='', max_length=100, verbose_name='Client IP')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('creator', models.CharField(max_length=255, verbose_name='Creator')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Challenge',
                'verbose_name_plural': 'MFA Challenges',
                'db_table': 'mfa_challenge',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MFAEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=100, verbose_name='OpenID')),
                ('label', models.CharField(default='Authenticator app', max_length=255, verbose_name='Label')),
                ('method', models.CharField(choices=[('TOTP', 'Authenticator app')], default='TOTP', max_length=32, verbose_name='Method')),
                ('encrypted_secret', models.TextField(verbose_name='Encrypted Secret')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Primary Enrollment')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('creator', models.CharField(max_length=255, verbose_name='Creator')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Enrollment',
                'verbose_name_plural': 'MFA Enrollments',
                'db_table': 'mfa_enrollment',
                'ordering': ['-is_primary', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='MFARecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(db_index=True, max_length=100, verbose_name='OpenID')),
                ('code_hash', models.CharField(max_length=255, verbose_name='Code Hash')),
                ('code_hint', models.CharField(max_length=16, verbose_name='Code Hint')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('creator', models.CharField(max_length=255, verbose_name='Creator')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='mfa.mfaenrollment')),
            ],
            options={
                'verbose_name': 'MFA Recovery Code',
                'verbose_name_plural': 'MFA Recovery Codes',
                'db_table': 'mfa_recovery_code',
                'ordering': ['id'],
            },
        ),
    ]
