# Generated by Django 5.2.12 on 2026-03-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("partners", "0002_customeraccount_operational_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("barcode", models.CharField(blank=True, default="", max_length=128)),
                ("unit_of_measure", models.CharField(blank=True, default="EA", max_length=32)),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("organization_id", "sku", "id"),
                "permissions": [("manage_products", "Can manage products")],
            },
        ),
        migrations.CreateModel(
            name="DistributionProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_sku", models.CharField(max_length=64)),
                ("external_name", models.CharField(blank=True, default="", max_length=255)),
                ("channel_name", models.CharField(blank=True, default="", max_length=100)),
                ("allow_dropshipping_orders", models.BooleanField(default=True)),
                ("allow_inbound_goods", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "customer_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_products",
                        to="partners.customeraccount",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_products",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ("product_id", "customer_account_id", "external_sku", "id"),
                "permissions": [("manage_distribution_products", "Can manage distribution products")],
            },
        ),
        migrations.CreateModel(
            name="ProductMark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mark_type",
                    models.CharField(
                        choices=[
                            ("FRAGILE", "Fragile"),
                            ("BATTERY", "Battery"),
                            ("TEMPERATURE", "Temperature Controlled"),
                            ("LABEL", "Label"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ("product_id", "mark_type", "value", "id"),
                "permissions": [("manage_product_marks", "Can manage product marks")],
            },
        ),
        migrations.CreateModel(
            name="ProductPackaging",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("UNIT", "Unit"),
                            ("INNER", "Inner Pack"),
                            ("CARTON", "Carton"),
                            ("PALLET", "Pallet"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="UNIT",
                        max_length=20,
                    ),
                ),
                ("package_code", models.CharField(max_length=50)),
                ("units_per_package", models.PositiveIntegerField(default=1)),
                ("length_cm", models.DecimalField(decimal_places=2, default="0.00", max_digits=10)),
                ("width_cm", models.DecimalField(decimal_places=2, default="0.00", max_digits=10)),
                ("height_cm", models.DecimalField(decimal_places=2, default="0.00", max_digits=10)),
                ("weight_kg", models.DecimalField(decimal_places=2, default="0.00", max_digits=10)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packaging_options",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ("product_id", "-is_default", "package_code", "id"),
                "permissions": [("manage_packaging", "Can manage product packaging")],
            },
        ),
        migrations.CreateModel(
            name="ProductSerialConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tracking_mode",
                    models.CharField(
                        choices=[("NONE", "None"), ("OPTIONAL", "Optional"), ("REQUIRED", "Required")],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("serial_pattern", models.CharField(blank=True, default="", max_length=255)),
                ("requires_uniqueness", models.BooleanField(default=True)),
                ("capture_on_inbound", models.BooleanField(default=False)),
                ("capture_on_outbound", models.BooleanField(default=False)),
                ("capture_on_returns", models.BooleanField(default=False)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serial_config",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "permissions": [("manage_serial_management", "Can manage product serial configuration")],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("organization", "sku"),
                name="unique_product_sku_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="distributionproduct",
            constraint=models.UniqueConstraint(
                fields=("product", "customer_account", "external_sku"),
                name="unique_distribution_product_per_customer_sku",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmark",
            constraint=models.UniqueConstraint(
                fields=("product", "mark_type", "value"),
                name="unique_product_mark_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpackaging",
            constraint=models.UniqueConstraint(
                fields=("product", "package_code"),
                name="unique_product_packaging_code",
            ),
        ),
    ]
