# Generated by Django 5.2.12 on 2026-03-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name', 'id')},
        ),
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'ordering': ('organization_id', 'user_id', 'id')},
        ),
    ]
