# Generated by Codex on 2026-03-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
        ("organizations", "0002_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationInvite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("staff_name", models.CharField(max_length=255)),
                ("staff_type", models.CharField(max_length=255)),
                ("check_code", models.PositiveIntegerField(default=8888)),
                ("is_company_admin", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("invite_token", models.CharField(max_length=255, unique=True)),
                ("invite_message", models.TextField(blank=True, default="")),
                ("invited_by", models.CharField(blank=True, default="", max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "accepted_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invites",
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "created_by_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_invites",
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "default_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_invites",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ("-create_time", "-id")},
        ),
        migrations.CreateModel(
            name="OrganizationPasswordReset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reset_token", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("issued_by", models.CharField(blank=True, default="", max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ("-create_time", "-id")},
        ),
        migrations.CreateModel(
            name="OrganizationStaffProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("staff_name", models.CharField(max_length=255)),
                ("staff_type", models.CharField(max_length=255)),
                ("check_code", models.PositiveIntegerField(default=8888)),
                ("is_lock", models.BooleanField(default=False)),
                ("error_check_code_counter", models.PositiveIntegerField(default=0)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "default_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_staff_profiles",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "membership",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={"ordering": ("organization_id", "staff_name", "id")},
        ),
        migrations.CreateModel(
            name="OrganizationAccessAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("MEMBERSHIP_CREATED", "Membership created"),
                            ("MEMBERSHIP_UPDATED", "Membership updated"),
                            ("MEMBERSHIP_SWITCHED", "Membership switched"),
                            ("STAFF_DIRECTORY_CREATED", "Staff directory created"),
                            ("STAFF_DIRECTORY_UPDATED", "Staff directory updated"),
                            ("INVITE_CREATED", "Invite created"),
                            ("INVITE_REVOKED", "Invite revoked"),
                            ("PASSWORD_RESET_ISSUED", "Password reset issued"),
                            ("PASSWORD_RESET_REVOKED", "Password reset revoked"),
                        ],
                        max_length=64,
                    ),
                ),
                ("actor_name", models.CharField(blank=True, default="", max_length=255)),
                ("target_identifier", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "invite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="organizations.organizationinvite",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_audit_events",
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_audit_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "password_reset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="organizations.organizationpasswordreset",
                    ),
                ),
            ],
            options={"ordering": ("-occurred_at", "-id")},
        ),
    ]
