# Generated by Codex on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_security_admin_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationaccessauditevent",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("MEMBERSHIP_CREATED", "Membership created"),
                    ("MEMBERSHIP_UPDATED", "Membership updated"),
                    ("MEMBERSHIP_SWITCHED", "Membership switched"),
                    ("STAFF_DIRECTORY_CREATED", "Staff directory created"),
                    ("STAFF_DIRECTORY_UPDATED", "Staff directory updated"),
                    ("INVITE_CREATED", "Invite created"),
                    ("INVITE_REVOKED", "Invite revoked"),
                    ("INVITE_ACCEPTED", "Invite accepted"),
                    ("PASSWORD_RESET_ISSUED", "Password reset issued"),
                    ("PASSWORD_RESET_COMPLETED", "Password reset completed"),
                    ("PASSWORD_RESET_REVOKED", "Password reset revoked"),
                ],
                max_length=64,
            ),
        ),
    ]
