# Generated by Django 5.2.12 on 2026-03-24 02:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_organizationaccessauditevent_action_type'),
        ('products', '0002_alter_productpackaging_height_cm_and_more'),
        ('warehouse', '0002_alter_warehouse_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('target_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_rules', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_rules', to='products.product')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_rules_source', to='locations.location')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_rules_target', to='locations.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_rules', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', 'priority', 'warehouse_id', 'target_location_id', 'product_id', 'id'),
                'permissions': [('manage_replenishment', 'Can manage replenishment rules and tasks')],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=64)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('priority', models.PositiveIntegerField(default=100)),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('completed_by', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_replenishment_tasks', to='organizations.organizationmembership')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_tasks_from', to='locations.location')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_tasks', to='inventory.inventorymovement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_tasks', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_tasks', to='products.product')),
                ('replenishment_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='transfers.replenishmentrule')),
                ('source_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_tasks', to='inventory.inventorybalance')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_tasks_to', to='locations.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishment_tasks', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', 'status', 'priority', 'generated_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=64)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('reference_code', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_orders', to='organizations.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_orders', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('organization_id', '-create_time', '-id'),
                'permissions': [('view_transfers', 'Can view transfer operations'), ('manage_transfer_orders', 'Can manage transfer orders')],
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('requested_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('moved_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32)),
                ('lot_number', models.CharField(blank=True, default='', max_length=64)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32)),
                ('completed_by', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('assigned_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transfer_lines', to='organizations.organizationmembership')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines_from', to='locations.location')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_lines', to='inventory.inventorymovement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines', to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines', to='products.product')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines_to', to='locations.location')),
                ('transfer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transfers.transferorder')),
            ],
            options={
                'ordering': ('organization_id', 'transfer_order_id', 'line_number', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='replenishmentrule',
            constraint=models.UniqueConstraint(fields=('organization', 'warehouse', 'product', 'source_location', 'target_location', 'stock_status'), name='unique_replenishment_rule_definition'),
        ),
        migrations.AddConstraint(
            model_name='replenishmentrule',
            constraint=models.CheckConstraint(condition=models.Q(('target_qty__gt', models.F('minimum_qty'))), name='replenishment_target_qty_gt_minimum_qty'),
        ),
        migrations.AddConstraint(
            model_name='replenishmenttask',
            constraint=models.UniqueConstraint(fields=('organization', 'task_number'), name='unique_replenishment_task_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='transferorder',
            constraint=models.UniqueConstraint(fields=('organization', 'transfer_number'), name='unique_transfer_order_number_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='transferline',
            constraint=models.UniqueConstraint(fields=('transfer_order', 'line_number'), name='unique_transfer_line_number_per_order'),
        ),
        migrations.AddConstraint(
            model_name='transferline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_qty__gte', models.F('moved_qty'))), name='transfer_requested_qty_gte_moved_qty'),
        ),
    ]
