# Generated by Django 5.2.12 on 2026-03-13 14:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0002_rename_creater_creator'),
        ('inventory', '0002_inventoryadjustmentreason_and_more'),
        ('locations', '0001_initial'),
        ('staff', '0002_rename_creater_creator'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplenishmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('minimum_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Minimum Qty')),
                ('target_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Target Qty')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_rules', to='goods.listmodel', verbose_name='Goods')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_rules_source', to='locations.location', verbose_name='Source Location')),
                ('target_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_rules_target', to='locations.location', verbose_name='Target Location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_rules', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Replenishment Rule',
                'verbose_name_plural': 'Replenishment Rules',
                'db_table': 'transfers_replenishment_rule',
                'ordering': ['priority', 'warehouse_id', 'target_location_id', 'goods_id'],
            },
        ),
        migrations.CreateModel(
            name='ReplenishmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('task_number', models.CharField(max_length=64, verbose_name='Task Number')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantity')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('completed_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Completed By')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Generated At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_tasks', to='staff.listmodel', verbose_name='Assigned To')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_tasks_from', to='locations.location', verbose_name='From Location')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_tasks', to='goods.listmodel', verbose_name='Goods')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_tasks', to='inventory.inventorymovement', verbose_name='Inventory Movement')),
                ('replenishment_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='transfers.replenishmentrule', verbose_name='Replenishment Rule')),
                ('source_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_tasks', to='inventory.inventorybalance', verbose_name='Source Balance')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_tasks_to', to='locations.location', verbose_name='To Location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishment_tasks', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Replenishment Task',
                'verbose_name_plural': 'Replenishment Tasks',
                'db_table': 'transfers_replenishment_task',
                'ordering': ['status', 'priority', 'generated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('transfer_number', models.CharField(max_length=64, verbose_name='Transfer Number')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='Requested Date')),
                ('reference_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Reference Code')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_orders', to='warehouse.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Transfer Order',
                'verbose_name_plural': 'Transfer Orders',
                'db_table': 'transfers_transfer_order',
                'ordering': ['-create_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='system', max_length=255, verbose_name='Created By')),
                ('openid', models.CharField(db_index=True, max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Label')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('line_number', models.PositiveIntegerField(verbose_name='Line Number')),
                ('requested_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Requested Qty')),
                ('moved_qty', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Moved Qty')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('QUARANTINE', 'Quarantine'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=32, verbose_name='Stock Status')),
                ('lot_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Lot Number')),
                ('serial_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial Number')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=32, verbose_name='Status')),
                ('completed_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Completed By')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='staff.listmodel', verbose_name='Assigned To')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines_from', to='locations.location', verbose_name='From Location')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='goods.listmodel', verbose_name='Goods')),
                ('inventory_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='inventory.inventorymovement', verbose_name='Inventory Movement')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines_to', to='locations.location', verbose_name='To Location')),
                ('transfer_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='transfers.transferorder', verbose_name='Transfer Order')),
            ],
            options={
                'verbose_name': 'Transfer Line',
                'verbose_name_plural': 'Transfer Lines',
                'db_table': 'transfers_transfer_line',
                'ordering': ['transfer_order_id', 'line_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='replenishmentrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'warehouse', 'goods', 'source_location', 'target_location', 'stock_status'), name='transfers_replenishment_rule_uq'),
        ),
        migrations.AddConstraint(
            model_name='replenishmentrule',
            constraint=models.CheckConstraint(condition=models.Q(('target_qty__gt', models.F('minimum_qty'))), name='transfers_replenishment_target_gt_min'),
        ),
        migrations.AddConstraint(
            model_name='replenishmenttask',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'task_number'), name='transfers_replenishment_task_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='transferorder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('openid', 'transfer_number'), name='transfers_transfer_order_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='transferline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_delete', False)), fields=('transfer_order', 'line_number'), name='transfers_transfer_line_number_uq'),
        ),
        migrations.AddConstraint(
            model_name='transferline',
            constraint=models.CheckConstraint(condition=models.Q(('requested_qty__gte', models.F('moved_qty'))), name='transfers_transfer_requested_gte_moved'),
        ),
    ]
